# PROFIL
profile_coach = Profile.create(first_name: "Coach", last_name: "Family Name", role: "Coach" )
user_coach = User.create(email: "coach@gmail.com", password: "password", profile: profile_coach)

profile_adrien = Profile.create(first_name: "Adrien", last_name: "Cassan", role: "Athlete")
user_adrien = User.create(email: "adrien.cassan@gmail.com", password: "password", profile: profile_adrien)

# RESULT
result1 = Result.new(profile: profile_adrien, date: "2017-09-12", weight: 76.1, fatmass: 15)
result1.remote_selfie_url = "http://res.cloudinary.com/duojdxafe/image/upload/v1536851762/2017-09-12.jpg"
result1.save!

result2 = Result.new(profile: profile_adrien, date: "2018-04-03", weight: 75, fatmass: 13.6)
result2.remote_selfie_url = "http://res.cloudinary.com/duojdxafe/image/upload/v1536851764/2018-04-03.jpg"
result2.save!

result3 = Result.new(profile: profile_adrien, date: "2018-06-18", weight: 74.6, fatmass: 14)
result3.remote_selfie_url = "http://res.cloudinary.com/duojdxafe/image/upload/v1536851762/2018-06-18.jpg"
result3.save!

result4 = Result.new(profile: profile_adrien, date: "2018-08-26", weight: 78.7, fatmass: 10.6)
result4.remote_selfie_url = "http://res.cloudinary.com/duojdxafe/image/upload/v1536851763/2018-08-26.jpg"
result4.save!

# EXERCICES
Exercice.create(name: 'Smith Machine Squats', nameEN: 'Smith Machine Squats')
Exercice.create(name: 'Leg Extensions', nameEN: 'Leg Extensions')
Exercice.create(name: 'Walking Lunges', nameEN: 'Walking Lunges')
Exercice.create(name: 'Leg Presses', nameEN: 'Leg Presses')
Exercice.create(name: 'Cable Flys', nameEN: 'Cable Flys')
Exercice.create(name: 'Barbell Back Presses', nameEN: 'Barbell Back Presses')
Exercice.create(name: 'Dumbbell Front Raises', nameEN: 'Dumbbell Front Raises')
Exercice.create(name: 'Tirage horizontal', nameEN: 'Tirage horizontal')
Exercice.create(name: 'Machine Presses', nameEN: 'Machine Presses')
Exercice.create(name: 'Dumbbell Shrugs', nameEN: 'Dumbbell Shrugs')
Exercice.create(name: 'Rowing vertical', nameEN: 'Rowing vertical')
Exercice.create(name: 'Bent-Over Dumbbell Lateral Raises', nameEN: 'Bent-Over Dumbbell Lateral Raises')
Exercice.create(name: 'Developpe Militaire', nameEN: 'Developpe Militaire')
Exercice.create(name: 'Barbell Bench Presses', nameEN: 'Barbell Bench Presses')
Exercice.create(name: 'Incline Dumbbell Flys', nameEN: 'Incline Dumbbell Flys')
Exercice.create(name: 'Hammer Curls', nameEN: 'Hammer Curls')
Exercice.create(name: 'Incline Barbell Bench Presses', nameEN: 'Incline Barbell Bench Presses')
Exercice.create(name: 'Barbell Curls', nameEN: 'Barbell Curls')
Exercice.create(name: 'Machine Flys', nameEN: 'Machine Flys')
Exercice.create(name: 'Push-Ups', nameEN: 'Push-Ups')
Exercice.create(name: 'TRX calins', nameEN: 'TRX calins')
Exercice.create(name: 'Concentration Curls', nameEN: 'Concentration Curls')
Exercice.create(name: 'TRX Biceps', nameEN: 'TRX Biceps')
Exercice.create(name: 'Machine Bench Presses', nameEN: 'Machine Bench Presses')
Exercice.create(name: 'Poulis Basse', nameEN: 'Poulis Basse')
Exercice.create(name: 'Chin-Ups', nameEN: 'Chin-Ups')
Exercice.create(name: 'Parallel Bar Dips', nameEN: 'Parallel Bar Dips')
Exercice.create(name: 'Close-Grip Barbell Bench Presses', nameEN: 'Close-Grip Barbell Bench Presses')
Exercice.create(name: 'Lat Pull-Downs', nameEN: 'Lat Pull-Downs')
Exercice.create(name: 'Poulie Verticale', nameEN: 'Poulie Verticale')
Exercice.create(name: 'Back Extensions', nameEN: 'Back Extensions')
Exercice.create(name: 'Close-Grip Lat Pull-Downs', nameEN: 'Close-Grip Lat Pull-Downs')
Exercice.create(name: 'Barbell Deadlifts', nameEN: 'Barbell Deadlifts')
Exercice.create(name: 'Push-Downs', nameEN: 'Push-Downs')
Exercice.create(name: 'T-Bar Rows', nameEN: 'T-Bar Rows')
Exercice.create(name: 'Extensions triceps Poulie Reverse', nameEN: 'Extensions triceps Poulie Reverse')
Exercice.create(name: 'Lying Barbell Triceps Extensions', nameEN: 'Lying Barbell Triceps Extensions')
Exercice.create(name: 'Barbell Rows', nameEN: 'Barbell Rows')
Exercice.create(name: 'Reverse Chin-Ups', nameEN: 'Reverse Chin-Ups')
Exercice.create(name: 'TRX Push-up Large', nameEN: 'TRX Push-up Large')
Exercice.create(name: 'Swing au Kettle bell', nameEN: 'Swing au Kettle bell')

# WORKOUTS
Workout.create(date: '2018-09-09', profile: profile_adrien, name: 'Pectoraux & Jambes')
Workout.create(date: '2018-09-08', profile: profile_adrien, name: 'Epaules & Trapezes')
Workout.create(date: '2018-09-04', profile: profile_adrien, name: 'Epaules & Trapezes')
Workout.create(date: '2018-09-01', profile: profile_adrien, name: 'Pectoraux & Dos')
Workout.create(date: '2018-08-30', profile: profile_adrien, name: 'Pectoraux & Biceps')
Workout.create(date: '2018-08-26', profile: profile_adrien, name: 'Pectoraux & Biceps')
Workout.create(date: '2018-08-23', profile: profile_adrien, name: 'Dos & Triceps')
Workout.create(date: '2018-08-21', profile: profile_adrien, name: 'Pectoraux & Biceps')
Workout.create(date: '2018-08-18', profile: profile_adrien, name: 'Pectoraux & Biceps')
Workout.create(date: '2018-08-18', profile: profile_adrien, name: 'Pectoraux & Jambes')
Workout.create(date: '2018-08-17', profile: profile_adrien, name: 'Epaules & Trapezes')
Workout.create(date: '2018-08-16', profile: profile_adrien, name: 'Pectoraux & Dos')
Workout.create(date: '2018-08-14', profile: profile_adrien, name: 'Dos & Triceps')
Workout.create(date: '2018-08-11', profile: profile_adrien, name: 'Pectoraux & Biceps')
Workout.create(date: '2018-08-10', profile: profile_adrien, name: 'Epaules & Trapezes')
Workout.create(date: '2018-08-06', profile: profile_adrien, name: 'Pectoraux & Dos')
Workout.create(date: '2018-08-03', profile: profile_adrien, name: 'Pectoraux & Biceps')
Workout.create(date: '2018-08-01', profile: profile_adrien, name: 'Dos & Triceps')
Workout.create(date: '2018-07-30', profile: profile_adrien, name: 'Pectoraux & Biceps')
Workout.create(date: '2018-07-28', profile: profile_adrien, name: 'Pectoraux & Dos')
Workout.create(date: '2018-07-26', profile: profile_adrien, name: 'Epaules & Trapezes')
Workout.create(date: '2018-07-25', profile: profile_adrien, name: 'Pectoraux & Biceps')
Workout.create(date: '2018-07-23', profile: profile_adrien, name: 'Dos & Triceps')
Workout.create(date: '2018-07-20', profile: profile_adrien, name: 'Epaules & Trapezes')
Workout.create(date: '2018-07-20', profile: profile_adrien, name: 'Dos & Triceps')
Workout.create(date: '2018-07-17', profile: profile_adrien, name: 'Dos & Triceps')
Workout.create(date: '2018-07-13', profile: profile_adrien, name: 'Epaules & Trapezes')
Workout.create(date: '2018-06-20', profile: profile_adrien, name: 'Epaules & Trapezes')

# WORKOUSETS
Workouset.create(workout:1, exercice:1)
Workouset.create(workout:1, exercice:2)
Workouset.create(workout:1, exercice:3)
Workouset.create(workout:1, exercice:4)
Workouset.create(workout:1, exercice:5)
Workouset.create(workout:2, exercice:6)
Workouset.create(workout:2, exercice:7)
Workouset.create(workout:2, exercice:8)
Workouset.create(workout:2, exercice:9)
Workouset.create(workout:2, exercice:10)
Workouset.create(workout:2, exercice:11)
Workouset.create(workout:2, exercice:12)
Workouset.create(workout:3, exercice:6)
Workouset.create(workout:3, exercice:13)
Workouset.create(workout:3, exercice:11)
Workouset.create(workout:3, exercice:8)
Workouset.create(workout:3, exercice:7)
Workouset.create(workout:3, exercice:10)
Workouset.create(workout:3, exercice:9)
Workouset.create(workout:3, exercice:12)
Workouset.create(workout:4, exercice:14)
Workouset.create(workout:4, exercice:15)
Workouset.create(workout:5, exercice:14)
Workouset.create(workout:5, exercice:16)
Workouset.create(workout:5, exercice:17)
Workouset.create(workout:5, exercice:18)
Workouset.create(workout:5, exercice:19)
Workouset.create(workout:5, exercice:20)
Workouset.create(workout:5, exercice:5)
Workouset.create(workout:5, exercice:21)
Workouset.create(workout:5, exercice:22)
Workouset.create(workout:5, exercice:23)
Workouset.create(workout:5, exercice:24)
Workouset.create(workout:5, exercice:25)
Workouset.create(workout:6, exercice:14)
Workouset.create(workout:7, exercice:26)
Workouset.create(workout:7, exercice:27)
Workouset.create(workout:7, exercice:28)
Workouset.create(workout:7, exercice:29)
Workouset.create(workout:7, exercice:30)
Workouset.create(workout:7, exercice:31)
Workouset.create(workout:7, exercice:32)
Workouset.create(workout:7, exercice:33)
Workouset.create(workout:7, exercice:34)
Workouset.create(workout:7, exercice:35)
Workouset.create(workout:7, exercice:36)
Workouset.create(workout:7, exercice:37)
Workouset.create(workout:8, exercice:14)
Workouset.create(workout:8, exercice:17)
Workouset.create(workout:8, exercice:16)
Workouset.create(workout:8, exercice:18)
Workouset.create(workout:8, exercice:25)
Workouset.create(workout:8, exercice:22)
Workouset.create(workout:8, exercice:5)
Workouset.create(workout:8, exercice:21)
Workouset.create(workout:8, exercice:20)
Workouset.create(workout:8, exercice:23)
Workouset.create(workout:8, exercice:19)
Workouset.create(workout:8, exercice:24)
Workouset.create(workout:9, exercice:14)
Workouset.create(workout:9, exercice:17)
Workouset.create(workout:10, exercice:1)
Workouset.create(workout:10, exercice:5)
Workouset.create(workout:11, exercice:13)
Workouset.create(workout:11, exercice:8)
Workouset.create(workout:11, exercice:11)
Workouset.create(workout:11, exercice:7)
Workouset.create(workout:11, exercice:10)
Workouset.create(workout:11, exercice:12)
Workouset.create(workout:12, exercice:14)
Workouset.create(workout:12, exercice:15)
Workouset.create(workout:12, exercice:38)
Workouset.create(workout:12, exercice:29)
Workouset.create(workout:12, exercice:39)
Workouset.create(workout:12, exercice:40)
Workouset.create(workout:12, exercice:33)
Workouset.create(workout:13, exercice:33)
Workouset.create(workout:13, exercice:32)
Workouset.create(workout:13, exercice:34)
Workouset.create(workout:13, exercice:36)
Workouset.create(workout:13, exercice:28)
Workouset.create(workout:13, exercice:37)
Workouset.create(workout:14, exercice:14)
Workouset.create(workout:14, exercice:17)
Workouset.create(workout:14, exercice:16)
Workouset.create(workout:14, exercice:18)
Workouset.create(workout:14, exercice:5)
Workouset.create(workout:14, exercice:24)
Workouset.create(workout:14, exercice:22)
Workouset.create(workout:14, exercice:20)
Workouset.create(workout:14, exercice:21)
Workouset.create(workout:14, exercice:23)
Workouset.create(workout:14, exercice:19)
Workouset.create(workout:15, exercice:6)
Workouset.create(workout:15, exercice:7)
Workouset.create(workout:15, exercice:11)
Workouset.create(workout:15, exercice:8)
Workouset.create(workout:15, exercice:10)
Workouset.create(workout:15, exercice:9)
Workouset.create(workout:16, exercice:14)
Workouset.create(workout:16, exercice:39)
Workouset.create(workout:16, exercice:29)
Workouset.create(workout:16, exercice:15)
Workouset.create(workout:16, exercice:38)
Workouset.create(workout:16, exercice:40)
Workouset.create(workout:16, exercice:33)
Workouset.create(workout:17, exercice:14)
Workouset.create(workout:17, exercice:17)
Workouset.create(workout:17, exercice:16)
Workouset.create(workout:18, exercice:33)
Workouset.create(workout:18, exercice:28)
Workouset.create(workout:18, exercice:26)
Workouset.create(workout:18, exercice:27)
Workouset.create(workout:18, exercice:34)
Workouset.create(workout:18, exercice:36)
Workouset.create(workout:18, exercice:30)
Workouset.create(workout:19, exercice:14)
Workouset.create(workout:19, exercice:17)
Workouset.create(workout:19, exercice:18)
Workouset.create(workout:19, exercice:16)
Workouset.create(workout:19, exercice:19)
Workouset.create(workout:20, exercice:33)
Workouset.create(workout:20, exercice:14)
Workouset.create(workout:20, exercice:15)
Workouset.create(workout:20, exercice:38)
Workouset.create(workout:20, exercice:39)
Workouset.create(workout:20, exercice:40)
Workouset.create(workout:21, exercice:13)
Workouset.create(workout:21, exercice:11)
Workouset.create(workout:21, exercice:7)
Workouset.create(workout:21, exercice:10)
Workouset.create(workout:21, exercice:12)
Workouset.create(workout:21, exercice:41)
Workouset.create(workout:22, exercice:17)
Workouset.create(workout:22, exercice:14)
Workouset.create(workout:22, exercice:16)
Workouset.create(workout:22, exercice:5)
Workouset.create(workout:22, exercice:22)
Workouset.create(workout:22, exercice:21)
Workouset.create(workout:22, exercice:23)
Workouset.create(workout:22, exercice:20)
Workouset.create(workout:22, exercice:18)
Workouset.create(workout:22, exercice:19)
Workouset.create(workout:23, exercice:33)
Workouset.create(workout:23, exercice:32)
Workouset.create(workout:23, exercice:27)
Workouset.create(workout:23, exercice:26)
Workouset.create(workout:23, exercice:28)
Workouset.create(workout:23, exercice:34)
Workouset.create(workout:23, exercice:36)
Workouset.create(workout:23, exercice:29)
Workouset.create(workout:23, exercice:35)
Workouset.create(workout:24, exercice:13)
Workouset.create(workout:24, exercice:7)
Workouset.create(workout:24, exercice:12)
Workouset.create(workout:24, exercice:11)
Workouset.create(workout:24, exercice:41)
Workouset.create(workout:24, exercice:10)
Workouset.create(workout:25, exercice:29)
Workouset.create(workout:26, exercice:26)
Workouset.create(workout:26, exercice:33)
Workouset.create(workout:26, exercice:32)
Workouset.create(workout:26, exercice:27)
Workouset.create(workout:26, exercice:28)
Workouset.create(workout:26, exercice:34)
Workouset.create(workout:27, exercice:13)
Workouset.create(workout:27, exercice:7)
Workouset.create(workout:27, exercice:12)
Workouset.create(workout:27, exercice:11)
Workouset.create(workout:27, exercice:41)
Workouset.create(workout:27, exercice:10)
Workouset.create(workout:28, exercice:13)
Workouset.create(workout:28, exercice:7)
Workouset.create(workout:28, exercice:12)
Workouset.create(workout:28, exercice:11)
Workouset.create(workout:28, exercice:10)

# REPETITIONS
Repetition.create(workouset:1, quantity:10, weight:50)
Repetition.create(workouset:1, quantity:10, weight:50)
Repetition.create(workouset:1, quantity:10, weight:50)
Repetition.create(workouset:1, quantity:10, weight:50)
Repetition.create(workouset:2, quantity:10, weight:50)
Repetition.create(workouset:2, quantity:10, weight:55)
Repetition.create(workouset:2, quantity:10, weight:59)
Repetition.create(workouset:2, quantity:10, weight:64)
Repetition.create(workouset:3, quantity:10, weight:24)
Repetition.create(workouset:3, quantity:10, weight:24)
Repetition.create(workouset:3, quantity:10, weight:24)
Repetition.create(workouset:3, quantity:10, weight:24)
Repetition.create(workouset:4, quantity:10, weight:70)
Repetition.create(workouset:4, quantity:10, weight:70)
Repetition.create(workouset:4, quantity:10, weight:70)
Repetition.create(workouset:4, quantity:10, weight:80)
Repetition.create(workouset:6, quantity:10, weight:50)
Repetition.create(workouset:7, quantity:10, weight:10)
Repetition.create(workouset:7, quantity:10, weight:10)
Repetition.create(workouset:7, quantity:10, weight:10)
Repetition.create(workouset:6, quantity:9, weight:50)
Repetition.create(workouset:6, quantity:8, weight:50)
Repetition.create(workouset:6, quantity:10, weight:45)
Repetition.create(workouset:7, quantity:10, weight:10)
Repetition.create(workouset:8, quantity:10, weight:77)
Repetition.create(workouset:8, quantity:10, weight:77)
Repetition.create(workouset:8, quantity:10, weight:77)
Repetition.create(workouset:8, quantity:10, weight:77)
Repetition.create(workouset:9, quantity:10, weight:55)
Repetition.create(workouset:10, quantity:10, weight:50)
Repetition.create(workouset:10, quantity:10, weight:50)
Repetition.create(workouset:9, quantity:10, weight:59)
Repetition.create(workouset:9, quantity:10, weight:59)
Repetition.create(workouset:10, quantity:10, weight:50)
Repetition.create(workouset:9, quantity:10, weight:59)
Repetition.create(workouset:10, quantity:10, weight:50)
Repetition.create(workouset:11, quantity:10, weight:25)
Repetition.create(workouset:11, quantity:10, weight:30)
Repetition.create(workouset:11, quantity:10, weight:30)
Repetition.create(workouset:11, quantity:10, weight:30)
Repetition.create(workouset:12, quantity:8, weight:8)
Repetition.create(workouset:12, quantity:10, weight:6)
Repetition.create(workouset:13, quantity:10, weight:50)
Repetition.create(workouset:13, quantity:10, weight:45)
Repetition.create(workouset:13, quantity:10, weight:45)
Repetition.create(workouset:13, quantity:10, weight:45)
Repetition.create(workouset:14, quantity:8, weight:20)
Repetition.create(workouset:15, quantity:10, weight:35)
Repetition.create(workouset:15, quantity:10, weight:35)
Repetition.create(workouset:14, quantity:8, weight:18)
Repetition.create(workouset:14, quantity:8, weight:18)
Repetition.create(workouset:15, quantity:8, weight:35)
Repetition.create(workouset:15, quantity:8, weight:35)
Repetition.create(workouset:14, quantity:8, weight:18)
Repetition.create(workouset:16, quantity:10, weight:64)
Repetition.create(workouset:16, quantity:10, weight:73)
Repetition.create(workouset:16, quantity:10, weight:77)
Repetition.create(workouset:16, quantity:10, weight:77)
Repetition.create(workouset:17, quantity:10, weight:8)
Repetition.create(workouset:17, quantity:12, weight:8)
Repetition.create(workouset:17, quantity:12, weight:8)
Repetition.create(workouset:21, quantity:11, weight:75)
Repetition.create(workouset:21, quantity:10, weight:80)
Repetition.create(workouset:21, quantity:9, weight:80)
Repetition.create(workouset:21, quantity:6, weight:80)
Repetition.create(workouset:21, quantity:4, weight:75)
Repetition.create(workouset:22, quantity:10, weight:24)
Repetition.create(workouset:22, quantity:10, weight:24)
Repetition.create(workouset:22, quantity:10, weight:24)
Repetition.create(workouset:23, quantity:10, weight:75)
Repetition.create(workouset:23, quantity:10, weight:75)
Repetition.create(workouset:24, quantity:10, weight:14)
Repetition.create(workouset:24, quantity:10, weight:14)
Repetition.create(workouset:23, quantity:5, weight:75)
Repetition.create(workouset:24, quantity:10, weight:14)
Repetition.create(workouset:25, quantity:10, weight:65)
Repetition.create(workouset:25, quantity:9, weight:65)
Repetition.create(workouset:25, quantity:5, weight:55)
Repetition.create(workouset:25, quantity:3, weight:60)
Repetition.create(workouset:25, quantity:9, weight:60)
Repetition.create(workouset:26, quantity:10, weight:35)
Repetition.create(workouset:26, quantity:10, weight:35)
Repetition.create(workouset:26, quantity:10, weight:35)
Repetition.create(workouset:26, quantity:10, weight:35)
Repetition.create(workouset:27, quantity:10, weight:64)
Repetition.create(workouset:28, quantity:12, weight:0)
Repetition.create(workouset:27, quantity:10, weight:68)
Repetition.create(workouset:28, quantity:8, weight:0)
Repetition.create(workouset:28, quantity:8, weight:0)
Repetition.create(workouset:27, quantity:9, weight:68)
Repetition.create(workouset:23, quantity:10, weight:75)
Repetition.create(workouset:24, quantity:10, weight:14)
Repetition.create(workouset:35, quantity:10, weight:75)
Repetition.create(workouset:35, quantity:10, weight:75)
Repetition.create(workouset:35, quantity:10, weight:75)
Repetition.create(workouset:35, quantity:5, weight:75)
Repetition.create(workouset:36, quantity:10, weight:0)
Repetition.create(workouset:36, quantity:10, weight:0)
Repetition.create(workouset:37, quantity:10, weight:0)
Repetition.create(workouset:37, quantity:8, weight:8)
Repetition.create(workouset:36, quantity:10, weight:0)
Repetition.create(workouset:37, quantity:10, weight:8)
Repetition.create(workouset:37, quantity:10, weight:8)
Repetition.create(workouset:36, quantity:10, weight:14)
Repetition.create(workouset:38, quantity:8, weight:55)
Repetition.create(workouset:38, quantity:10, weight:50)
Repetition.create(workouset:38, quantity:8, weight:50)
Repetition.create(workouset:39, quantity:10, weight:49)
Repetition.create(workouset:40, quantity:10, weight:45)
Repetition.create(workouset:40, quantity:10, weight:45)
Repetition.create(workouset:39, quantity:10, weight:54)
Repetition.create(workouset:41, quantity:15, weight:12)
Repetition.create(workouset:41, quantity:15, weight:12)
Repetition.create(workouset:41, quantity:15, weight:12)
Repetition.create(workouset:41, quantity:15, weight:12)
Repetition.create(workouset:39, quantity:10, weight:54)
Repetition.create(workouset:40, quantity:10, weight:45)
Repetition.create(workouset:40, quantity:10, weight:45)
Repetition.create(workouset:39, quantity:10, weight:54)
Repetition.create(workouset:42, quantity:10, weight:52)
Repetition.create(workouset:42, quantity:9, weight:59)
Repetition.create(workouset:42, quantity:9, weight:59)
Repetition.create(workouset:48, quantity:8, weight:80)
Repetition.create(workouset:48, quantity:9, weight:75)
Repetition.create(workouset:48, quantity:5, weight:70)
Repetition.create(workouset:48, quantity:4, weight:70)
Repetition.create(workouset:48, quantity:9, weight:70)
Repetition.create(workouset:49, quantity:9, weight:60)
Repetition.create(workouset:50, quantity:10, weight:14)
Repetition.create(workouset:49, quantity:8, weight:60)
Repetition.create(workouset:50, quantity:10, weight:14)
Repetition.create(workouset:49, quantity:10, weight:55)
Repetition.create(workouset:50, quantity:10, weight:14)
Repetition.create(workouset:50, quantity:10, weight:14)
Repetition.create(workouset:49, quantity:10, weight:60)
Repetition.create(workouset:51, quantity:10, weight:35)
Repetition.create(workouset:51, quantity:9, weight:35)
Repetition.create(workouset:51, quantity:5, weight:35)
Repetition.create(workouset:51, quantity:4, weight:32,5)
Repetition.create(workouset:51, quantity:11, weight:30)
Repetition.create(workouset:52, quantity:10, weight:20)
Repetition.create(workouset:52, quantity:10, weight:23)
Repetition.create(workouset:52, quantity:9, weight:23)
Repetition.create(workouset:52, quantity:10, weight:23)
Repetition.create(workouset:53, quantity:8, weight:12)
Repetition.create(workouset:60, quantity:10, weight:80)
Repetition.create(workouset:60, quantity:6, weight:80)
Repetition.create(workouset:60, quantity:4, weight:75)
Repetition.create(workouset:60, quantity:6, weight:75)
Repetition.create(workouset:60, quantity:4, weight:70)
Repetition.create(workouset:61, quantity:9, weight:60)
Repetition.create(workouset:61, quantity:9, weight:60)
Repetition.create(workouset:61, quantity:6, weight:60)
Repetition.create(workouset:61, quantity:10, weight:60)
Repetition.create(workouset:62, quantity:10, weight:50)
Repetition.create(workouset:62, quantity:10, weight:50)
Repetition.create(workouset:62, quantity:10, weight:50)
Repetition.create(workouset:62, quantity:10, weight:50)
Repetition.create(workouset:63, quantity:10, weight:27)
Repetition.create(workouset:63, quantity:10, weight:32)
Repetition.create(workouset:63, quantity:10, weight:27)
Repetition.create(workouset:63, quantity:10, weight:32)
Repetition.create(workouset:64, quantity:10, weight:20)
Repetition.create(workouset:64, quantity:10, weight:20)
Repetition.create(workouset:64, quantity:9, weight:20)
Repetition.create(workouset:64, quantity:9, weight:20)
Repetition.create(workouset:65, quantity:10, weight:64)
Repetition.create(workouset:65, quantity:10, weight:68)
Repetition.create(workouset:65, quantity:10, weight:68)
Repetition.create(workouset:65, quantity:10, weight:73)
Repetition.create(workouset:66, quantity:10, weight:35)
Repetition.create(workouset:66, quantity:10, weight:35)
Repetition.create(workouset:66, quantity:10, weight:35)
Repetition.create(workouset:66, quantity:10, weight:35)
Repetition.create(workouset:67, quantity:10, weight:14)
Repetition.create(workouset:67, quantity:10, weight:14)
Repetition.create(workouset:68, quantity:10, weight:50)
Repetition.create(workouset:68, quantity:10, weight:50)
Repetition.create(workouset:67, quantity:10, weight:14)
Repetition.create(workouset:68, quantity:10, weight:50)
Repetition.create(workouset:68, quantity:10, weight:50)
Repetition.create(workouset:67, quantity:10, weight:14)
Repetition.create(workouset:69, quantity:10, weight:6)
Repetition.create(workouset:69, quantity:10, weight:6)
Repetition.create(workouset:69, quantity:10, weight:6)
Repetition.create(workouset:70, quantity:10, weight:75)
Repetition.create(workouset:70, quantity:10, weight:75)
Repetition.create(workouset:70, quantity:8, weight:75)
Repetition.create(workouset:70, quantity:2, weight:70)
Repetition.create(workouset:70, quantity:5, weight:75)
Repetition.create(workouset:70, quantity:5, weight:70)
Repetition.create(workouset:71, quantity:10, weight:22)
Repetition.create(workouset:71, quantity:10, weight:22)
Repetition.create(workouset:71, quantity:10, weight:22)
Repetition.create(workouset:71, quantity:10, weight:22)
Repetition.create(workouset:72, quantity:10, weight:50)
Repetition.create(workouset:72, quantity:10, weight:55)
Repetition.create(workouset:72, quantity:10, weight:55)
Repetition.create(workouset:72, quantity:10, weight:55)
Repetition.create(workouset:73, quantity:10, weight:49)
Repetition.create(workouset:74, quantity:9, weight:0)
Repetition.create(workouset:74, quantity:9, weight:0)
Repetition.create(workouset:73, quantity:9, weight:49)
Repetition.create(workouset:73, quantity:9, weight:49)
Repetition.create(workouset:74, quantity:9, weight:0)
Repetition.create(workouset:74, quantity:5, weight:0)
Repetition.create(workouset:73, quantity:9, weight:49)
Repetition.create(workouset:77, quantity:10, weight:50)
Repetition.create(workouset:77, quantity:10, weight:50)
Repetition.create(workouset:77, quantity:10, weight:50)
Repetition.create(workouset:77, quantity:10, weight:50)
Repetition.create(workouset:78, quantity:10, weight:59)
Repetition.create(workouset:78, quantity:10, weight:59)
Repetition.create(workouset:78, quantity:10, weight:59)
Repetition.create(workouset:78, quantity:10, weight:59)
Repetition.create(workouset:79, quantity:10, weight:41)
Repetition.create(workouset:80, quantity:10, weight:41)
Repetition.create(workouset:79, quantity:10, weight:45)
Repetition.create(workouset:80, quantity:10, weight:45)
Repetition.create(workouset:80, quantity:9, weight:41)
Repetition.create(workouset:79, quantity:10, weight:41)
Repetition.create(workouset:81, quantity:10, weight:50)
Repetition.create(workouset:81, quantity:10, weight:55)
Repetition.create(workouset:81, quantity:10, weight:50)
Repetition.create(workouset:82, quantity:10, weight:25)
Repetition.create(workouset:82, quantity:10, weight:30)
Repetition.create(workouset:83, quantity:10, weight:70)
Repetition.create(workouset:83, quantity:10, weight:75)
Repetition.create(workouset:83, quantity:10, weight:75)
Repetition.create(workouset:83, quantity:9, weight:80)
Repetition.create(workouset:84, quantity:10, weight:60)
Repetition.create(workouset:85, quantity:10, weight:16)
Repetition.create(workouset:85, quantity:10, weight:16)
Repetition.create(workouset:84, quantity:10, weight:60)
Repetition.create(workouset:84, quantity:10, weight:60)
Repetition.create(workouset:85, quantity:10, weight:16)
Repetition.create(workouset:85, quantity:10, weight:16)
Repetition.create(workouset:84, quantity:8, weight:60)
Repetition.create(workouset:86, quantity:10, weight:30)
Repetition.create(workouset:86, quantity:10, weight:30)
Repetition.create(workouset:86, quantity:10, weight:30)
Repetition.create(workouset:86, quantity:8, weight:30)
Repetition.create(workouset:87, quantity:10, weight:27)
Repetition.create(workouset:87, quantity:10, weight:27)
Repetition.create(workouset:88, quantity:10, weight:68)
Repetition.create(workouset:88, quantity:10, weight:77)
Repetition.create(workouset:88, quantity:8, weight:77)
Repetition.create(workouset:88, quantity:10, weight:73)
Repetition.create(workouset:89, quantity:10, weight:14)
Repetition.create(workouset:90, quantity:15, weight:0)
Repetition.create(workouset:90, quantity:15, weight:0)
Repetition.create(workouset:90, quantity:15, weight:0)
Repetition.create(workouset:89, quantity:10, weight:12)
Repetition.create(workouset:89, quantity:10, weight:12)
Repetition.create(workouset:89, quantity:10, weight:12)
Repetition.create(workouset:91, quantity:10, weight:0)
Repetition.create(workouset:91, quantity:10, weight:0)
Repetition.create(workouset:94, quantity:10, weight:40)
Repetition.create(workouset:94, quantity:10, weight:50)
Repetition.create(workouset:95, quantity:10, weight:14)
Repetition.create(workouset:95, quantity:10, weight:14)
Repetition.create(workouset:95, quantity:10, weight:14)
Repetition.create(workouset:94, quantity:10, weight:50)
Repetition.create(workouset:95, quantity:10, weight:14)
Repetition.create(workouset:94, quantity:10, weight:50)
Repetition.create(workouset:96, quantity:10, weight:30)
Repetition.create(workouset:96, quantity:10, weight:35)
Repetition.create(workouset:96, quantity:10, weight:30)
Repetition.create(workouset:96, quantity:10, weight:30)
Repetition.create(workouset:97, quantity:10, weight:59)
Repetition.create(workouset:97, quantity:10, weight:59)
Repetition.create(workouset:97, quantity:10, weight:64)
Repetition.create(workouset:97, quantity:10, weight:68)
Repetition.create(workouset:98, quantity:10, weight:50)
Repetition.create(workouset:98, quantity:10, weight:50)
Repetition.create(workouset:98, quantity:10, weight:50)
Repetition.create(workouset:98, quantity:10, weight:50)
Repetition.create(workouset:99, quantity:10, weight:50)
Repetition.create(workouset:99, quantity:10, weight:55)
Repetition.create(workouset:99, quantity:10, weight:55)
Repetition.create(workouset:99, quantity:10, weight:55)
Repetition.create(workouset:100, quantity:10, weight:75)
Repetition.create(workouset:100, quantity:10, weight:75)
Repetition.create(workouset:100, quantity:10, weight:75)
Repetition.create(workouset:100, quantity:10, weight:75)
Repetition.create(workouset:101, quantity:10, weight:0)
Repetition.create(workouset:101, quantity:9, weight:0)
Repetition.create(workouset:102, quantity:10, weight:49)
Repetition.create(workouset:102, quantity:9, weight:49)
Repetition.create(workouset:101, quantity:5, weight:0)
Repetition.create(workouset:102, quantity:9, weight:49)
Repetition.create(workouset:101, quantity:6, weight:0)
Repetition.create(workouset:102, quantity:9, weight:49)
Repetition.create(workouset:103, quantity:10, weight:22)
Repetition.create(workouset:103, quantity:10, weight:22)
Repetition.create(workouset:103, quantity:10, weight:22)
Repetition.create(workouset:103, quantity:10, weight:22)
Repetition.create(workouset:104, quantity:10, weight:40)
Repetition.create(workouset:104, quantity:10, weight:40)
Repetition.create(workouset:104, quantity:10, weight:50)
Repetition.create(workouset:104, quantity:10, weight:50)
Repetition.create(workouset:107, quantity:10, weight:70)
Repetition.create(workouset:107, quantity:10, weight:75)
Repetition.create(workouset:107, quantity:10, weight:75)
Repetition.create(workouset:107, quantity:10, weight:75)
Repetition.create(workouset:108, quantity:10, weight:55)
Repetition.create(workouset:109, quantity:10, weight:14)
Repetition.create(workouset:109, quantity:10, weight:14)
Repetition.create(workouset:108, quantity:10, weight:55)
Repetition.create(workouset:108, quantity:10, weight:60)
Repetition.create(workouset:109, quantity:10, weight:14)
Repetition.create(workouset:109, quantity:10, weight:16)
Repetition.create(workouset:108, quantity:8, weight:60)
Repetition.create(workouset:110, quantity:10, weight:55)
Repetition.create(workouset:110, quantity:10, weight:55)
Repetition.create(workouset:110, quantity:10, weight:60)
Repetition.create(workouset:110, quantity:10, weight:60)
Repetition.create(workouset:111, quantity:10, weight:50)
Repetition.create(workouset:111, quantity:10, weight:55)
Repetition.create(workouset:111, quantity:10, weight:55)
Repetition.create(workouset:112, quantity:10, weight:14)
Repetition.create(workouset:112, quantity:10, weight:14)
Repetition.create(workouset:113, quantity:10, weight:4)
Repetition.create(workouset:113, quantity:10, weight:4)
Repetition.create(workouset:113, quantity:10, weight:4)
Repetition.create(workouset:112, quantity:10, weight:14)
Repetition.create(workouset:112, quantity:10, weight:14)
Repetition.create(workouset:113, quantity:10, weight:4)
Repetition.create(workouset:114, quantity:10, weight:41)
Repetition.create(workouset:115, quantity:10, weight:41)
Repetition.create(workouset:114, quantity:10, weight:41)
Repetition.create(workouset:115, quantity:10, weight:41)
Repetition.create(workouset:114, quantity:10, weight:41)
Repetition.create(workouset:115, quantity:9, weight:41)
Repetition.create(workouset:116, quantity:10, weight:45)
Repetition.create(workouset:116, quantity:10, weight:59)
Repetition.create(workouset:116, quantity:10, weight:59)
Repetition.create(workouset:117, quantity:10, weight:60)
Repetition.create(workouset:117, quantity:10, weight:60)
Repetition.create(workouset:117, quantity:10, weight:70)
Repetition.create(workouset:117, quantity:10, weight:70)
Repetition.create(workouset:118, quantity:10, weight:55)
Repetition.create(workouset:118, quantity:10, weight:55)
Repetition.create(workouset:118, quantity:10, weight:55)
Repetition.create(workouset:118, quantity:8, weight:55)
Repetition.create(workouset:119, quantity:10, weight:35)
Repetition.create(workouset:119, quantity:10, weight:35)
Repetition.create(workouset:119, quantity:10, weight:35)
Repetition.create(workouset:119, quantity:8, weight:35)
Repetition.create(workouset:120, quantity:10, weight:12)
Repetition.create(workouset:120, quantity:10, weight:12)
Repetition.create(workouset:121, quantity:10, weight:59)
Repetition.create(workouset:121, quantity:10, weight:64)
Repetition.create(workouset:121, quantity:10, weight:64)
Repetition.create(workouset:120, quantity:10, weight:14)
Repetition.create(workouset:122, quantity:10, weight:60)
Repetition.create(workouset:122, quantity:10, weight:60)
Repetition.create(workouset:122, quantity:10, weight:60)
Repetition.create(workouset:122, quantity:10, weight:60)
Repetition.create(workouset:123, quantity:10, weight:60)
Repetition.create(workouset:123, quantity:10, weight:65)
Repetition.create(workouset:123, quantity:10, weight:65)
Repetition.create(workouset:123, quantity:8, weight:65)
Repetition.create(workouset:123, quantity:3, weight:60)
Repetition.create(workouset:124, quantity:10, weight:22)
Repetition.create(workouset:124, quantity:10, weight:22)
Repetition.create(workouset:124, quantity:10, weight:22)
Repetition.create(workouset:124, quantity:10, weight:22)
Repetition.create(workouset:125, quantity:10, weight:40)
Repetition.create(workouset:125, quantity:10, weight:40)
Repetition.create(workouset:125, quantity:10, weight:40)
Repetition.create(workouset:125, quantity:10, weight:40)
Repetition.create(workouset:126, quantity:9, weight:0)
Repetition.create(workouset:126, quantity:9, weight:0)
Repetition.create(workouset:126, quantity:10, weight:0)
Repetition.create(workouset:126, quantity:10, weight:0)
Repetition.create(workouset:127, quantity:15, weight:0)
Repetition.create(workouset:127, quantity:15, weight:0)
Repetition.create(workouset:127, quantity:12, weight:0)
Repetition.create(workouset:127, quantity:10, weight:0)
Repetition.create(workouset:128, quantity:10, weight:18)
Repetition.create(workouset:128, quantity:9, weight:20)
Repetition.create(workouset:128, quantity:10, weight:20)
Repetition.create(workouset:128, quantity:8, weight:20)
Repetition.create(workouset:128, quantity:2, weight:18)
Repetition.create(workouset:129, quantity:10, weight:30)
Repetition.create(workouset:129, quantity:10, weight:30)
Repetition.create(workouset:129, quantity:10, weight:30)
Repetition.create(workouset:130, quantity:10, weight:12)
Repetition.create(workouset:130, quantity:10, weight:14)
Repetition.create(workouset:129, quantity:10, weight:30)
Repetition.create(workouset:130, quantity:10, weight:14)
Repetition.create(workouset:131, quantity:10, weight:50)
Repetition.create(workouset:131, quantity:10, weight:50)
Repetition.create(workouset:130, quantity:10, weight:14)
Repetition.create(workouset:131, quantity:10, weight:50)
Repetition.create(workouset:131, quantity:10, weight:50)
Repetition.create(workouset:132, quantity:10, weight:6)
Repetition.create(workouset:132, quantity:10, weight:6)
Repetition.create(workouset:132, quantity:10, weight:6)
Repetition.create(workouset:132, quantity:10, weight:6)
Repetition.create(workouset:133, quantity:10, weight:20)
Repetition.create(workouset:133, quantity:10, weight:20)
Repetition.create(workouset:133, quantity:10, weight:20)
Repetition.create(workouset:133, quantity:10, weight:20)
Repetition.create(workouset:134, quantity:10, weight:55)
Repetition.create(workouset:134, quantity:10, weight:55)
Repetition.create(workouset:134, quantity:10, weight:55)
Repetition.create(workouset:134, quantity:8, weight:55)
Repetition.create(workouset:135, quantity:10, weight:60)
Repetition.create(workouset:136, quantity:10, weight:12)
Repetition.create(workouset:135, quantity:10, weight:65)
Repetition.create(workouset:136, quantity:10, weight:12)
Repetition.create(workouset:136, quantity:10, weight:14)
Repetition.create(workouset:135, quantity:10, weight:65)
Repetition.create(workouset:135, quantity:10, weight:65)
Repetition.create(workouset:136, quantity:10, weight:14)
Repetition.create(workouset:137, quantity:10, weight:27)
Repetition.create(workouset:137, quantity:10, weight:27)
Repetition.create(workouset:137, quantity:10, weight:20)
Repetition.create(workouset:137, quantity:10, weight:20)
Repetition.create(workouset:138, quantity:10, weight:12)
Repetition.create(workouset:138, quantity:10, weight:12)
Repetition.create(workouset:138, quantity:10, weight:12)
Repetition.create(workouset:138, quantity:10, weight:12)
Repetition.create(workouset:139, quantity:10, weight:0)
Repetition.create(workouset:140, quantity:10, weight:0)
Repetition.create(workouset:139, quantity:10, weight:0)
Repetition.create(workouset:140, quantity:10, weight:0)
Repetition.create(workouset:139, quantity:10, weight:0)
Repetition.create(workouset:139, quantity:10, weight:0)
Repetition.create(workouset:140, quantity:10, weight:0)
Repetition.create(workouset:140, quantity:10, weight:0)
Repetition.create(workouset:141, quantity:19, weight:0)
Repetition.create(workouset:141, quantity:15, weight:0)
Repetition.create(workouset:141, quantity:15, weight:0)
Repetition.create(workouset:144, quantity:10, weight:55)
Repetition.create(workouset:144, quantity:10, weight:55)
Repetition.create(workouset:144, quantity:10, weight:55)
Repetition.create(workouset:144, quantity:10, weight:55)
Repetition.create(workouset:145, quantity:10, weight:54)
Repetition.create(workouset:145, quantity:10, weight:59)
Repetition.create(workouset:145, quantity:10, weight:59)
Repetition.create(workouset:145, quantity:10, weight:59)
Repetition.create(workouset:146, quantity:10, weight:0)
Repetition.create(workouset:147, quantity:8, weight:9)
Repetition.create(workouset:147, quantity:9, weight:14)
Repetition.create(workouset:146, quantity:10, weight:0)
Repetition.create(workouset:146, quantity:10, weight:0)
Repetition.create(workouset:147, quantity:10, weight:14)
Repetition.create(workouset:147, quantity:10, weight:14)
Repetition.create(workouset:146, quantity:10, weight:0)
Repetition.create(workouset:148, quantity:10, weight:50)
Repetition.create(workouset:148, quantity:10, weight:50)
Repetition.create(workouset:148, quantity:10, weight:50)
Repetition.create(workouset:149, quantity:10, weight:40)
Repetition.create(workouset:150, quantity:10, weight:41)
Repetition.create(workouset:149, quantity:10, weight:41)
Repetition.create(workouset:150, quantity:10, weight:41)
Repetition.create(workouset:149, quantity:10, weight:41)
Repetition.create(workouset:150, quantity:9, weight:41)
Repetition.create(workouset:153, quantity:10, weight:18)
Repetition.create(workouset:153, quantity:10, weight:18)
Repetition.create(workouset:153, quantity:10, weight:18)
Repetition.create(workouset:153, quantity:10, weight:18)
Repetition.create(workouset:154, quantity:10, weight:12)
Repetition.create(workouset:154, quantity:10, weight:12)
Repetition.create(workouset:154, quantity:10, weight:12)
Repetition.create(workouset:154, quantity:10, weight:12)
Repetition.create(workouset:155, quantity:10, weight:6)
Repetition.create(workouset:155, quantity:10, weight:6)
Repetition.create(workouset:155, quantity:10, weight:4)
Repetition.create(workouset:155, quantity:10, weight:4)
Repetition.create(workouset:156, quantity:10, weight:25)
Repetition.create(workouset:156, quantity:10, weight:25)
Repetition.create(workouset:156, quantity:10, weight:25)
Repetition.create(workouset:156, quantity:10, weight:27,5)
Repetition.create(workouset:157, quantity:10, weight:20)
Repetition.create(workouset:157, quantity:10, weight:20)
Repetition.create(workouset:157, quantity:10, weight:20)
Repetition.create(workouset:157, quantity:10, weight:20)
Repetition.create(workouset:158, quantity:10, weight:50)
Repetition.create(workouset:158, quantity:10, weight:50)
Repetition.create(workouset:158, quantity:10, weight:50)
Repetition.create(workouset:158, quantity:10, weight:50)
Repetition.create(workouset:159, quantity:10, weight:45)
Repetition.create(workouset:159, quantity:10, weight:49)
Repetition.create(workouset:159, quantity:10, weight:49)
Repetition.create(workouset:159, quantity:10, weight:49)
Repetition.create(workouset:160, quantity:10, weight:0)
Repetition.create(workouset:160, quantity:10, weight:0)
Repetition.create(workouset:160, quantity:8, weight:0)
Repetition.create(workouset:160, quantity:6, weight:0)
Repetition.create(workouset:161, quantity:10, weight:50)
Repetition.create(workouset:161, quantity:10, weight:55)
Repetition.create(workouset:161, quantity:10, weight:55)
Repetition.create(workouset:161, quantity:10, weight:55)
Repetition.create(workouset:162, quantity:10, weight:36)
Repetition.create(workouset:162, quantity:10, weight:45)
Repetition.create(workouset:162, quantity:10, weight:49)
Repetition.create(workouset:162, quantity:10, weight:54)
Repetition.create(workouset:163, quantity:8, weight:8)
Repetition.create(workouset:163, quantity:10, weight:8)
Repetition.create(workouset:163, quantity:9, weight:8)
Repetition.create(workouset:163, quantity:10, weight:0)
Repetition.create(workouset:164, quantity:10, weight:40)
Repetition.create(workouset:164, quantity:10, weight:45)
Repetition.create(workouset:164, quantity:10, weight:50)
Repetition.create(workouset:165, quantity:10, weight:36)
Repetition.create(workouset:165, quantity:10, weight:41)
Repetition.create(workouset:165, quantity:10, weight:41)
Repetition.create(workouset:166, quantity:10, weight:16)
Repetition.create(workouset:166, quantity:10, weight:18)
Repetition.create(workouset:166, quantity:10, weight:18)
Repetition.create(workouset:166, quantity:10, weight:18)
Repetition.create(workouset:167, quantity:10, weight:8)
Repetition.create(workouset:167, quantity:10, weight:10)
Repetition.create(workouset:167, quantity:10, weight:10)
Repetition.create(workouset:167, quantity:10, weight:10)
Repetition.create(workouset:168, quantity:10, weight:6)
Repetition.create(workouset:168, quantity:10, weight:6)
Repetition.create(workouset:168, quantity:10, weight:6)
Repetition.create(workouset:168, quantity:10, weight:6)
Repetition.create(workouset:169, quantity:10, weight:25)
Repetition.create(workouset:169, quantity:10, weight:25)
Repetition.create(workouset:169, quantity:10, weight:25)
Repetition.create(workouset:169, quantity:10, weight:25)
Repetition.create(workouset:170, quantity:10, weight:16)
Repetition.create(workouset:170, quantity:10, weight:16)
Repetition.create(workouset:170, quantity:10, weight:16)
Repetition.create(workouset:170, quantity:10, weight:16)
Repetition.create(workouset:171, quantity:10, weight:50)
Repetition.create(workouset:171, quantity:10, weight:50)
Repetition.create(workouset:171, quantity:10, weight:50)
Repetition.create(workouset:171, quantity:10, weight:50)
Repetition.create(workouset:172, quantity:10, weight:16)
Repetition.create(workouset:172, quantity:10, weight:16)
Repetition.create(workouset:172, quantity:10, weight:16)
Repetition.create(workouset:172, quantity:10, weight:16)
Repetition.create(workouset:173, quantity:10, weight:10)
Repetition.create(workouset:173, quantity:10, weight:10)
Repetition.create(workouset:173, quantity:10, weight:10)
Repetition.create(workouset:173, quantity:10, weight:10)
Repetition.create(workouset:174, quantity:10, weight:6)
Repetition.create(workouset:174, quantity:10, weight:4)
Repetition.create(workouset:174, quantity:10, weight:4)
Repetition.create(workouset:174, quantity:10, weight:6)
Repetition.create(workouset:175, quantity:10, weight:20)
Repetition.create(workouset:175, quantity:10, weight:20)
Repetition.create(workouset:175, quantity:10, weight:20)
Repetition.create(workouset:175, quantity:10, weight:20)
Repetition.create(workouset:176, quantity:10, weight:40)
Repetition.create(workouset:176, quantity:10, weight:40)
Repetition.create(workouset:176, quantity:10, weight:40)
Repetition.create(workouset:176, quantity:10, weight:40)
