# PROFIL
profile_coach = Profile.create(first_name: "Coach", last_name: "Family Name", role: "Coach" )
user_coach = User.create(email: "coach@gmail.com", password: "password", profile: profile_coach)

profile_adrien = Profile.create(first_name: "Adrien", last_name: "Cassan", role: "Athlete")
user_adrien = User.create(email: "adrien.cassan@gmail.com", password: "password", profile: profile_adrien)

# RESULT
result1 = Result.new(profile: profile_adrien, date: "2017-09-12", weight: 76.1, fatmass: 15)
result1.remote_selfie_url = "http://res.cloudinary.com/duojdxafe/image/upload/v1536851762/2017-09-12.jpg"
result1.save!

result2 = Result.new(profile: profile_adrien, date: "2018-04-03", weight: 75, fatmass: 13.6)
result2.remote_selfie_url = "http://res.cloudinary.com/duojdxafe/image/upload/v1536851764/2018-04-03.jpg"
result2.save!

result3 = Result.new(profile: profile_adrien, date: "2018-06-18", weight: 74.6, fatmass: 14)
result3.remote_selfie_url = "http://res.cloudinary.com/duojdxafe/image/upload/v1536851762/2018-06-18.jpg"
result3.save!

result4 = Result.new(profile: profile_adrien, date: "2018-08-26", weight: 78.7, fatmass: 10.6)
result4.remote_selfie_url = "http://res.cloudinary.com/duojdxafe/image/upload/v1536851763/2018-08-26.jpg"
result4.save!

# EXERCICES
Exercice.create(id: 1, name: 'Smith Machine Squats', nameEN: 'Smith Machine Squats')
Exercice.create(id: 2, name: 'Leg Extensions', nameEN: 'Leg Extensions')
Exercice.create(id: 3, name: 'Walking Lunges', nameEN: 'Walking Lunges')
Exercice.create(id: 4, name: 'Leg Presses', nameEN: 'Leg Presses')
Exercice.create(id: 5, name: 'Cable Flys', nameEN: 'Cable Flys')
Exercice.create(id: 6, name: 'Barbell Back Presses', nameEN: 'Barbell Back Presses')
Exercice.create(id: 7, name: 'Dumbbell Front Raises', nameEN: 'Dumbbell Front Raises')
Exercice.create(id: 8, name: 'Tirage horizontal', nameEN: 'Tirage horizontal')
Exercice.create(id: 9, name: 'Machine Presses', nameEN: 'Machine Presses')
Exercice.create(id: 10, name: 'Dumbbell Shrugs', nameEN: 'Dumbbell Shrugs')
Exercice.create(id: 11, name: 'Rowing vertical', nameEN: 'Rowing vertical')
Exercice.create(id: 12, name: 'Bent-Over Dumbbell Lateral Raises', nameEN: 'Bent-Over Dumbbell Lateral Raises')
Exercice.create(id: 13, name: 'Developpe Militaire', nameEN: 'Developpe Militaire')
Exercice.create(id: 14, name: 'Barbell Bench Presses', nameEN: 'Barbell Bench Presses')
Exercice.create(id: 15, name: 'Incline Dumbbell Flys', nameEN: 'Incline Dumbbell Flys')
Exercice.create(id: 16, name: 'Hammer Curls', nameEN: 'Hammer Curls')
Exercice.create(id: 17, name: 'Incline Barbell Bench Presses', nameEN: 'Incline Barbell Bench Presses')
Exercice.create(id: 18, name: 'Barbell Curls', nameEN: 'Barbell Curls')
Exercice.create(id: 19, name: 'Machine Flys', nameEN: 'Machine Flys')
Exercice.create(id: 20, name: 'Push-Ups', nameEN: 'Push-Ups')
Exercice.create(id: 21, name: 'TRX calins', nameEN: 'TRX calins')
Exercice.create(id: 22, name: 'Concentration Curls', nameEN: 'Concentration Curls')
Exercice.create(id: 23, name: 'TRX Biceps', nameEN: 'TRX Biceps')
Exercice.create(id: 24, name: 'Machine Bench Presses', nameEN: 'Machine Bench Presses')
Exercice.create(id: 25, name: 'Poulis Basse', nameEN: 'Poulis Basse')
Exercice.create(id: 26, name: 'Chin-Ups', nameEN: 'Chin-Ups')
Exercice.create(id: 27, name: 'Parallel Bar Dips', nameEN: 'Parallel Bar Dips')
Exercice.create(id: 28, name: 'Close-Grip Barbell Bench Presses', nameEN: 'Close-Grip Barbell Bench Presses')
Exercice.create(id: 29, name: 'Lat Pull-Downs', nameEN: 'Lat Pull-Downs')
Exercice.create(id: 30, name: 'Poulie Verticale', nameEN: 'Poulie Verticale')
Exercice.create(id: 31, name: 'Back Extensions', nameEN: 'Back Extensions')
Exercice.create(id: 32, name: 'Close-Grip Lat Pull-Downs', nameEN: 'Close-Grip Lat Pull-Downs')
Exercice.create(id: 33, name: 'Barbell Deadlifts', nameEN: 'Barbell Deadlifts')
Exercice.create(id: 39, name: 'Reverse Chin-Ups', nameEN: 'Reverse Chin-Ups')
Exercice.create(id: 40, name: 'TRX Push-up Large', nameEN: 'TRX Push-up Large')
Exercice.create(id: 41, name: 'Swing au Kettle bell', nameEN: 'Swing au Kettle bell')
Exercice.create(id: 42, name: 'Barbell Rows', nameEN: 'Barbell Rows')
Exercice.create(id: 43, name: 'Extensions triceps Poulie Reverse', nameEN: 'Extensions triceps Poulie Reverse')
Exercice.create(id: 44, name: 'Lying Barbell Triceps Extensions', nameEN: 'Lying Barbell Triceps Extensions')
Exercice.create(id: 45, name: 'Push-Downs', nameEN: 'Push-Downs')


# WORKOUT
Workout.create(id: 1, profile: profile_adrien, name: 'Dos & Triceps', is_template: true)
Workout.create(id: 2, profile: profile_adrien, name: 'Epaules & Trapezes', is_template: true)
Workout.create(id: 3, profile: profile_adrien, name: 'Pectoraux & Biceps', is_template: true)
Workout.create(id: 4, profile: profile_adrien, name: 'Pectoraux & Dos', is_template: true)
Workout.create(id: 5, profile: profile_adrien, name: 'Pectoraux & Jambes', is_template: true)
Workout.create(id: 6, date: '2018-09-09', profile: profile_adrien, name: 'Pectoraux & Jambes', is_template: false)
Workout.create(id: 7, date: '2018-09-08', profile: profile_adrien, name: 'Epaules & Trapezes', is_template: false)
Workout.create(id: 8, date: '2018-09-04', profile: profile_adrien, name: 'Epaules & Trapezes', is_template: false)
Workout.create(id: 9, date: '2018-09-01', profile: profile_adrien, name: 'Pectoraux & Dos', is_template: false)
Workout.create(id: 10, date: '2018-08-30', profile: profile_adrien, name: 'Pectoraux & Biceps', is_template: false)
Workout.create(id: 11, date: '2018-08-26', profile: profile_adrien, name: 'Pectoraux & Biceps', is_template: false)
Workout.create(id: 12, date: '2018-08-23', profile: profile_adrien, name: 'Dos & Triceps', is_template: false)
Workout.create(id: 13, date: '2018-08-21', profile: profile_adrien, name: 'Pectoraux & Biceps', is_template: false)
Workout.create(id: 14, date: '2018-08-18', profile: profile_adrien, name: 'Pectoraux & Biceps', is_template: false)
Workout.create(id: 15, date: '2018-08-18', profile: profile_adrien, name: 'Pectoraux & Jambes', is_template: false)
Workout.create(id: 16, date: '2018-08-17', profile: profile_adrien, name: 'Epaules & Trapezes', is_template: false)
Workout.create(id: 17, date: '2018-08-16', profile: profile_adrien, name: 'Pectoraux & Dos', is_template: false)
Workout.create(id: 18, date: '2018-08-14', profile: profile_adrien, name: 'Dos & Triceps', is_template: false)
Workout.create(id: 19, date: '2018-08-11', profile: profile_adrien, name: 'Pectoraux & Biceps', is_template: false)
Workout.create(id: 20, date: '2018-08-10', profile: profile_adrien, name: 'Epaules & Trapezes', is_template: false)
Workout.create(id: 21, date: '2018-08-06', profile: profile_adrien, name: 'Pectoraux & Dos', is_template: false)
Workout.create(id: 22, date: '2018-08-03', profile: profile_adrien, name: 'Pectoraux & Biceps', is_template: false)
Workout.create(id: 23, date: '2018-08-01', profile: profile_adrien, name: 'Dos & Triceps', is_template: false)
Workout.create(id: 24, date: '2018-07-30', profile: profile_adrien, name: 'Pectoraux & Biceps', is_template: false)
Workout.create(id: 25, date: '2018-07-28', profile: profile_adrien, name: 'Pectoraux & Dos', is_template: false)
Workout.create(id: 26, date: '2018-07-26', profile: profile_adrien, name: 'Epaules & Trapezes', is_template: false)
Workout.create(id: 27, date: '2018-07-25', profile: profile_adrien, name: 'Pectoraux & Biceps', is_template: false)
Workout.create(id: 28, date: '2018-07-23', profile: profile_adrien, name: 'Dos & Triceps', is_template: false)
Workout.create(id: 29, date: '2018-07-20', profile: profile_adrien, name: 'Epaules & Trapezes', is_template: false)
Workout.create(id: 30, date: '2018-07-20', profile: profile_adrien, name: 'Dos & Triceps', is_template: false)
Workout.create(id: 31, date: '2018-07-17', profile: profile_adrien, name: 'Dos & Triceps', is_template: false)
Workout.create(id: 32, date: '2018-07-13', profile: profile_adrien, name: 'Epaules & Trapezes', is_template: false)
Workout.create(id: 33, date: '2018-06-20', profile: profile_adrien, name: 'Epaules & Trapezes', is_template: false)

#
Workoutset.create(id: 1, workout_id:1, exercice_id:31)
Workoutset.create(id: 2, workout_id:2, exercice_id:6)
Workoutset.create(id: 3, workout_id:3, exercice_id:14)
Workoutset.create(id: 4, workout_id:4, exercice_id:14)
Workoutset.create(id: 5, workout_id:3, exercice_id:18)
Workoutset.create(id: 6, workout_id:1, exercice_id:33)
Workoutset.create(id: 7, workout_id:4, exercice_id:33)
Workoutset.create(id: 8, workout_id:4, exercice_id:42)
Workoutset.create(id: 9, workout_id:2, exercice_id:12)
Workoutset.create(id: 10, workout_id:3, exercice_id:5)
Workoutset.create(id: 11, workout_id:5, exercice_id:5)
Workoutset.create(id: 12, workout_id:1, exercice_id:26)
Workoutset.create(id: 13, workout_id:1, exercice_id:28)
Workoutset.create(id: 14, workout_id:1, exercice_id:32)
Workoutset.create(id: 15, workout_id:3, exercice_id:22)
Workoutset.create(id: 16, workout_id:2, exercice_id:13)
Workoutset.create(id: 17, workout_id:2, exercice_id:7)
Workoutset.create(id: 18, workout_id:2, exercice_id:10)
Workoutset.create(id: 19, workout_id:1, exercice_id:43)
Workoutset.create(id: 20, workout_id:3, exercice_id:16)
Workoutset.create(id: 21, workout_id:3, exercice_id:17)
Workoutset.create(id: 22, workout_id:4, exercice_id:15)
Workoutset.create(id: 23, workout_id:1, exercice_id:29)
Workoutset.create(id: 24, workout_id:4, exercice_id:29)
Workoutset.create(id: 25, workout_id:5, exercice_id:2)
Workoutset.create(id: 26, workout_id:5, exercice_id:4)
Workoutset.create(id: 27, workout_id:1, exercice_id:44)
Workoutset.create(id: 28, workout_id:3, exercice_id:24)
Workoutset.create(id: 29, workout_id:3, exercice_id:19)
Workoutset.create(id: 30, workout_id:2, exercice_id:9)
Workoutset.create(id: 31, workout_id:1, exercice_id:27)
Workoutset.create(id: 32, workout_id:1, exercice_id:30)
Workoutset.create(id: 33, workout_id:3, exercice_id:25)
Workoutset.create(id: 34, workout_id:1, exercice_id:45)
Workoutset.create(id: 35, workout_id:3, exercice_id:20)
Workoutset.create(id: 36, workout_id:4, exercice_id:39)
Workoutset.create(id: 37, workout_id:2, exercice_id:11)
Workoutset.create(id: 38, workout_id:5, exercice_id:1)
Workoutset.create(id: 39, workout_id:2, exercice_id:41)
Workoutset.create(id: 40, workout_id:2, exercice_id:8)
Workoutset.create(id: 41, workout_id:3, exercice_id:23)
Workoutset.create(id: 42, workout_id:3, exercice_id:21)
Workoutset.create(id: 43, workout_id:4, exercice_id:40)
Workoutset.create(id: 44, workout_id:5, exercice_id:3)
Workoutset.create(id: 45, workout_id:6, exercice_id:1)
Workoutset.create(id: 46, workout_id:6, exercice_id:2)
Workoutset.create(id: 47, workout_id:6, exercice_id:3)
Workoutset.create(id: 48, workout_id:6, exercice_id:4)
Workoutset.create(id: 49, workout_id:6, exercice_id:5)
Workoutset.create(id: 50, workout_id:7, exercice_id:6)
Workoutset.create(id: 51, workout_id:7, exercice_id:7)
Workoutset.create(id: 52, workout_id:7, exercice_id:8)
Workoutset.create(id: 53, workout_id:7, exercice_id:9)
Workoutset.create(id: 54, workout_id:7, exercice_id:10)
Workoutset.create(id: 55, workout_id:7, exercice_id:11)
Workoutset.create(id: 56, workout_id:7, exercice_id:12)
Workoutset.create(id: 57, workout_id:8, exercice_id:6)
Workoutset.create(id: 58, workout_id:8, exercice_id:13)
Workoutset.create(id: 59, workout_id:8, exercice_id:11)
Workoutset.create(id: 60, workout_id:8, exercice_id:8)
Workoutset.create(id: 61, workout_id:8, exercice_id:7)
Workoutset.create(id: 62, workout_id:8, exercice_id:10)
Workoutset.create(id: 63, workout_id:8, exercice_id:9)
Workoutset.create(id: 64, workout_id:8, exercice_id:12)
Workoutset.create(id: 65, workout_id:9, exercice_id:14)
Workoutset.create(id: 66, workout_id:9, exercice_id:15)
Workoutset.create(id: 67, workout_id:10, exercice_id:14)
Workoutset.create(id: 68, workout_id:10, exercice_id:16)
Workoutset.create(id: 69, workout_id:10, exercice_id:17)
Workoutset.create(id: 70, workout_id:10, exercice_id:18)
Workoutset.create(id: 71, workout_id:10, exercice_id:19)
Workoutset.create(id: 72, workout_id:10, exercice_id:20)
Workoutset.create(id: 73, workout_id:10, exercice_id:5)
Workoutset.create(id: 74, workout_id:10, exercice_id:21)
Workoutset.create(id: 75, workout_id:10, exercice_id:22)
Workoutset.create(id: 76, workout_id:10, exercice_id:23)
Workoutset.create(id: 77, workout_id:10, exercice_id:24)
Workoutset.create(id: 78, workout_id:12, exercice_id:29)
Workoutset.create(id: 79, workout_id:12, exercice_id:30)
Workoutset.create(id: 80, workout_id:12, exercice_id:31)
Workoutset.create(id: 81, workout_id:12, exercice_id:32)
Workoutset.create(id: 82, workout_id:12, exercice_id:33)
Workoutset.create(id: 83, workout_id:12, exercice_id:45)
Workoutset.create(id: 84, workout_id:12, exercice_id:43)
Workoutset.create(id: 85, workout_id:12, exercice_id:44)
Workoutset.create(id: 86, workout_id:13, exercice_id:14)
Workoutset.create(id: 87, workout_id:13, exercice_id:17)
Workoutset.create(id: 88, workout_id:13, exercice_id:16)
Workoutset.create(id: 89, workout_id:13, exercice_id:18)
Workoutset.create(id: 90, workout_id:13, exercice_id:25)
Workoutset.create(id: 91, workout_id:13, exercice_id:22)
Workoutset.create(id: 92, workout_id:13, exercice_id:5)
Workoutset.create(id: 93, workout_id:13, exercice_id:21)
Workoutset.create(id: 94, workout_id:13, exercice_id:20)
Workoutset.create(id: 95, workout_id:13, exercice_id:23)
Workoutset.create(id: 96, workout_id:13, exercice_id:19)
Workoutset.create(id: 97, workout_id:13, exercice_id:24)
Workoutset.create(id: 98, workout_id:14, exercice_id:14)
Workoutset.create(id: 99, workout_id:14, exercice_id:17)
Workoutset.create(id: 100, workout_id:15, exercice_id:1)
Workoutset.create(id: 101, workout_id:15, exercice_id:5)
Workoutset.create(id: 102, workout_id:16, exercice_id:13)
Workoutset.create(id: 103, workout_id:16, exercice_id:8)
Workoutset.create(id: 104, workout_id:16, exercice_id:11)
Workoutset.create(id: 105, workout_id:16, exercice_id:7)
Workoutset.create(id: 106, workout_id:16, exercice_id:10)
Workoutset.create(id: 107, workout_id:16, exercice_id:12)
Workoutset.create(id: 108, workout_id:17, exercice_id:14)
Workoutset.create(id: 109, workout_id:17, exercice_id:15)
Workoutset.create(id: 110, workout_id:17, exercice_id:42)
Workoutset.create(id: 111, workout_id:17, exercice_id:29)
Workoutset.create(id: 112, workout_id:17, exercice_id:39)
Workoutset.create(id: 113, workout_id:17, exercice_id:40)
Workoutset.create(id: 114, workout_id:17, exercice_id:33)
Workoutset.create(id: 115, workout_id:18, exercice_id:33)
Workoutset.create(id: 116, workout_id:18, exercice_id:32)
Workoutset.create(id: 117, workout_id:18, exercice_id:45)
Workoutset.create(id: 118, workout_id:18, exercice_id:43)
Workoutset.create(id: 119, workout_id:18, exercice_id:28)
Workoutset.create(id: 120, workout_id:18, exercice_id:44)
Workoutset.create(id: 121, workout_id:19, exercice_id:14)
Workoutset.create(id: 122, workout_id:19, exercice_id:17)
Workoutset.create(id: 123, workout_id:19, exercice_id:16)
Workoutset.create(id: 124, workout_id:19, exercice_id:18)
Workoutset.create(id: 125, workout_id:19, exercice_id:5)
Workoutset.create(id: 126, workout_id:19, exercice_id:24)
Workoutset.create(id: 127, workout_id:19, exercice_id:22)
Workoutset.create(id: 128, workout_id:19, exercice_id:20)
Workoutset.create(id: 129, workout_id:19, exercice_id:21)
Workoutset.create(id: 130, workout_id:19, exercice_id:23)
Workoutset.create(id: 131, workout_id:19, exercice_id:19)
Workoutset.create(id: 132, workout_id:20, exercice_id:6)
Workoutset.create(id: 133, workout_id:20, exercice_id:7)
Workoutset.create(id: 134, workout_id:20, exercice_id:11)
Workoutset.create(id: 135, workout_id:20, exercice_id:8)
Workoutset.create(id: 136, workout_id:20, exercice_id:10)
Workoutset.create(id: 137, workout_id:20, exercice_id:9)
Workoutset.create(id: 138, workout_id:21, exercice_id:14)
Workoutset.create(id: 139, workout_id:21, exercice_id:39)
Workoutset.create(id: 140, workout_id:21, exercice_id:29)
Workoutset.create(id: 141, workout_id:21, exercice_id:15)
Workoutset.create(id: 142, workout_id:21, exercice_id:42)
Workoutset.create(id: 143, workout_id:21, exercice_id:40)
Workoutset.create(id: 144, workout_id:21, exercice_id:33)
Workoutset.create(id: 145, workout_id:22, exercice_id:14)
Workoutset.create(id: 146, workout_id:22, exercice_id:17)
Workoutset.create(id: 147, workout_id:22, exercice_id:16)
Workoutset.create(id: 148, workout_id:23, exercice_id:33)
Workoutset.create(id: 149, workout_id:23, exercice_id:28)
Workoutset.create(id: 150, workout_id:23, exercice_id:26)
Workoutset.create(id: 151, workout_id:23, exercice_id:27)
Workoutset.create(id: 152, workout_id:23, exercice_id:45)
Workoutset.create(id: 153, workout_id:23, exercice_id:43)
Workoutset.create(id: 154, workout_id:23, exercice_id:30)
Workoutset.create(id: 155, workout_id:24, exercice_id:14)
Workoutset.create(id: 156, workout_id:24, exercice_id:17)
Workoutset.create(id: 157, workout_id:24, exercice_id:18)
Workoutset.create(id: 158, workout_id:24, exercice_id:16)
Workoutset.create(id: 159, workout_id:24, exercice_id:19)
Workoutset.create(id: 160, workout_id:25, exercice_id:33)
Workoutset.create(id: 161, workout_id:25, exercice_id:14)
Workoutset.create(id: 162, workout_id:25, exercice_id:15)
Workoutset.create(id: 163, workout_id:25, exercice_id:42)
Workoutset.create(id: 164, workout_id:25, exercice_id:39)
Workoutset.create(id: 165, workout_id:25, exercice_id:40)
Workoutset.create(id: 166, workout_id:26, exercice_id:13)
Workoutset.create(id: 167, workout_id:26, exercice_id:11)
Workoutset.create(id: 168, workout_id:26, exercice_id:7)
Workoutset.create(id: 169, workout_id:26, exercice_id:10)
Workoutset.create(id: 170, workout_id:26, exercice_id:12)
Workoutset.create(id: 171, workout_id:26, exercice_id:41)
Workoutset.create(id: 172, workout_id:27, exercice_id:17)
Workoutset.create(id: 173, workout_id:27, exercice_id:14)
Workoutset.create(id: 174, workout_id:27, exercice_id:16)
Workoutset.create(id: 175, workout_id:27, exercice_id:5)
Workoutset.create(id: 176, workout_id:27, exercice_id:22)
Workoutset.create(id: 177, workout_id:27, exercice_id:21)
Workoutset.create(id: 178, workout_id:27, exercice_id:23)
Workoutset.create(id: 179, workout_id:27, exercice_id:20)
Workoutset.create(id: 180, workout_id:27, exercice_id:18)
Workoutset.create(id: 181, workout_id:27, exercice_id:19)
Workoutset.create(id: 182, workout_id:28, exercice_id:33)
Workoutset.create(id: 183, workout_id:28, exercice_id:32)
Workoutset.create(id: 184, workout_id:28, exercice_id:27)
Workoutset.create(id: 185, workout_id:28, exercice_id:26)
Workoutset.create(id: 186, workout_id:28, exercice_id:28)
Workoutset.create(id: 187, workout_id:28, exercice_id:45)
Workoutset.create(id: 188, workout_id:28, exercice_id:43)
Workoutset.create(id: 189, workout_id:28, exercice_id:29)
Workoutset.create(id: 190, workout_id:29, exercice_id:13)
Workoutset.create(id: 191, workout_id:29, exercice_id:7)
Workoutset.create(id: 192, workout_id:29, exercice_id:12)
Workoutset.create(id: 193, workout_id:29, exercice_id:11)
Workoutset.create(id: 194, workout_id:29, exercice_id:41)
Workoutset.create(id: 195, workout_id:29, exercice_id:10)
Workoutset.create(id: 196, workout_id:30, exercice_id:29)
Workoutset.create(id: 197, workout_id:31, exercice_id:26)
Workoutset.create(id: 198, workout_id:31, exercice_id:33)
Workoutset.create(id: 199, workout_id:31, exercice_id:32)
Workoutset.create(id: 200, workout_id:31, exercice_id:27)
Workoutset.create(id: 201, workout_id:31, exercice_id:28)
Workoutset.create(id: 202, workout_id:31, exercice_id:45)
Workoutset.create(id: 203, workout_id:32, exercice_id:13)
Workoutset.create(id: 204, workout_id:32, exercice_id:7)
Workoutset.create(id: 205, workout_id:32, exercice_id:12)
Workoutset.create(id: 206, workout_id:32, exercice_id:11)
Workoutset.create(id: 207, workout_id:32, exercice_id:41)
Workoutset.create(id: 208, workout_id:32, exercice_id:10)
Workoutset.create(id: 209, workout_id:33, exercice_id:13)
Workoutset.create(id: 210, workout_id:33, exercice_id:7)
Workoutset.create(id: 211, workout_id:33, exercice_id:12)
Workoutset.create(id: 212, workout_id:33, exercice_id:11)
Workoutset.create(id: 213, workout_id:33, exercice_id:10)

Repetition.create(workoutset_id:45,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:45,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:45,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:45,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:46,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:46,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:46,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:46,  is_complete: true, quantity:10, weight:64.00)
Repetition.create(workoutset_id:47,  is_complete: true, quantity:10, weight:24.00)
Repetition.create(workoutset_id:47,  is_complete: true, quantity:10, weight:24.00)
Repetition.create(workoutset_id:47,  is_complete: true, quantity:10, weight:24.00)
Repetition.create(workoutset_id:47,  is_complete: true, quantity:10, weight:24.00)
Repetition.create(workoutset_id:48,  is_complete: true, quantity:10, weight:70.00)
Repetition.create(workoutset_id:48,  is_complete: true, quantity:10, weight:70.00)
Repetition.create(workoutset_id:48,  is_complete: true, quantity:10, weight:70.00)
Repetition.create(workoutset_id:48,  is_complete: true, quantity:10, weight:80.00)
Repetition.create(workoutset_id:50,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:51,  is_complete: true, quantity:10, weight:10.00)
Repetition.create(workoutset_id:51,  is_complete: true, quantity:10, weight:10.00)
Repetition.create(workoutset_id:51,  is_complete: true, quantity:10, weight:10.00)
Repetition.create(workoutset_id:50,  is_complete: true, quantity:9, weight:50.00)
Repetition.create(workoutset_id:50,  is_complete: true, quantity:8, weight:50.00)
Repetition.create(workoutset_id:50,  is_complete: true, quantity:10, weight:45.00)
Repetition.create(workoutset_id:51,  is_complete: true, quantity:10, weight:10.00)
Repetition.create(workoutset_id:52,  is_complete: true, quantity:10, weight:77.00)
Repetition.create(workoutset_id:52,  is_complete: true, quantity:10, weight:77.00)
Repetition.create(workoutset_id:52,  is_complete: true, quantity:10, weight:77.00)
Repetition.create(workoutset_id:52,  is_complete: true, quantity:10, weight:77.00)
Repetition.create(workoutset_id:53,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:54,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:54,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:53,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:53,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:54,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:53,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:54,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:55,  is_complete: true, quantity:10, weight:25.00)
Repetition.create(workoutset_id:55,  is_complete: true, quantity:10, weight:30.00)
Repetition.create(workoutset_id:55,  is_complete: true, quantity:10, weight:30.00)
Repetition.create(workoutset_id:55,  is_complete: true, quantity:10, weight:30.00)
Repetition.create(workoutset_id:56,  is_complete: true, quantity:8, weight:8.00)
Repetition.create(workoutset_id:56,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:57,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:57,  is_complete: true, quantity:10, weight:45.00)
Repetition.create(workoutset_id:57,  is_complete: true, quantity:10, weight:45.00)
Repetition.create(workoutset_id:57,  is_complete: true, quantity:10, weight:45.00)
Repetition.create(workoutset_id:58,  is_complete: true, quantity:8, weight:20.00)
Repetition.create(workoutset_id:59,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:59,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:58,  is_complete: true, quantity:8, weight:18.00)
Repetition.create(workoutset_id:58,  is_complete: true, quantity:8, weight:18.00)
Repetition.create(workoutset_id:59,  is_complete: true, quantity:8, weight:35.00)
Repetition.create(workoutset_id:59,  is_complete: true, quantity:8, weight:35.00)
Repetition.create(workoutset_id:58,  is_complete: true, quantity:8, weight:18.00)
Repetition.create(workoutset_id:60,  is_complete: true, quantity:10, weight:64.00)
Repetition.create(workoutset_id:60,  is_complete: true, quantity:10, weight:73.00)
Repetition.create(workoutset_id:60,  is_complete: true, quantity:10, weight:77.00)
Repetition.create(workoutset_id:60,  is_complete: true, quantity:10, weight:77.00)
Repetition.create(workoutset_id:61,  is_complete: true, quantity:10, weight:8.00)
Repetition.create(workoutset_id:61,  is_complete: true, quantity:12, weight:8.00)
Repetition.create(workoutset_id:61,  is_complete: true, quantity:12, weight:8.00)
Repetition.create(workoutset_id:65,  is_complete: true, quantity:11, weight:75.00)
Repetition.create(workoutset_id:65,  is_complete: true, quantity:10, weight:80.00)
Repetition.create(workoutset_id:65,  is_complete: true, quantity:9, weight:80.00)
Repetition.create(workoutset_id:65,  is_complete: true, quantity:6, weight:80.00)
Repetition.create(workoutset_id:65,  is_complete: true, quantity:4, weight:75.00)
Repetition.create(workoutset_id:66,  is_complete: true, quantity:10, weight:24.00)
Repetition.create(workoutset_id:66,  is_complete: true, quantity:10, weight:24.00)
Repetition.create(workoutset_id:66,  is_complete: true, quantity:10, weight:24.00)
Repetition.create(workoutset_id:67,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:67,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:68,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:68,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:67,  is_complete: true, quantity:5, weight:75.00)
Repetition.create(workoutset_id:68,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:69,  is_complete: true, quantity:10, weight:65.00)
Repetition.create(workoutset_id:69,  is_complete: true, quantity:9, weight:65.00)
Repetition.create(workoutset_id:69,  is_complete: true, quantity:5, weight:55.00)
Repetition.create(workoutset_id:69,  is_complete: true, quantity:3, weight:60.00)
Repetition.create(workoutset_id:69,  is_complete: true, quantity:9, weight:60.00)
Repetition.create(workoutset_id:70,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:70,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:70,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:70,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:71,  is_complete: true, quantity:10, weight:64.00)
Repetition.create(workoutset_id:72,  is_complete: true, quantity:12, weight:0.00)
Repetition.create(workoutset_id:71,  is_complete: true, quantity:10, weight:68.00)
Repetition.create(workoutset_id:72,  is_complete: true, quantity:8, weight:0.00)
Repetition.create(workoutset_id:72,  is_complete: true, quantity:8, weight:0.00)
Repetition.create(workoutset_id:71,  is_complete: true, quantity:9, weight:68.00)
Repetition.create(workoutset_id:67,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:68,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:78,  is_complete: true, quantity:10, weight:49.00)
Repetition.create(workoutset_id:79,  is_complete: true, quantity:10, weight:45.00)
Repetition.create(workoutset_id:79,  is_complete: true, quantity:10, weight:45.00)
Repetition.create(workoutset_id:78,  is_complete: true, quantity:10, weight:54.00)
Repetition.create(workoutset_id:80,  is_complete: true, quantity:15, weight:12.00)
Repetition.create(workoutset_id:80,  is_complete: true, quantity:15, weight:12.00)
Repetition.create(workoutset_id:80,  is_complete: true, quantity:15, weight:12.00)
Repetition.create(workoutset_id:80,  is_complete: true, quantity:15, weight:12.00)
Repetition.create(workoutset_id:78,  is_complete: true, quantity:10, weight:54.00)
Repetition.create(workoutset_id:79,  is_complete: true, quantity:10, weight:45.00)
Repetition.create(workoutset_id:79,  is_complete: true, quantity:10, weight:45.00)
Repetition.create(workoutset_id:78,  is_complete: true, quantity:10, weight:54.00)
Repetition.create(workoutset_id:81,  is_complete: true, quantity:10, weight:52.00)
Repetition.create(workoutset_id:81,  is_complete: true, quantity:9, weight:59.00)
Repetition.create(workoutset_id:81,  is_complete: true, quantity:9, weight:59.00)
Repetition.create(workoutset_id:86,  is_complete: true, quantity:8, weight:80.00)
Repetition.create(workoutset_id:86,  is_complete: true, quantity:9, weight:75.00)
Repetition.create(workoutset_id:86,  is_complete: true, quantity:5, weight:70.00)
Repetition.create(workoutset_id:86,  is_complete: true, quantity:4, weight:70.00)
Repetition.create(workoutset_id:86,  is_complete: true, quantity:9, weight:70.00)
Repetition.create(workoutset_id:87,  is_complete: true, quantity:9, weight:60.00)
Repetition.create(workoutset_id:88,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:87,  is_complete: true, quantity:8, weight:60.00)
Repetition.create(workoutset_id:88,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:87,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:88,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:88,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:87,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:89,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:89,  is_complete: true, quantity:9, weight:35.00)
Repetition.create(workoutset_id:89,  is_complete: true, quantity:5, weight:35.00)
Repetition.create(workoutset_id:89,  is_complete: true, quantity:4, weight:32.50)
Repetition.create(workoutset_id:89,  is_complete: true, quantity:11, weight:30.00)
Repetition.create(workoutset_id:90,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:90,  is_complete: true, quantity:10, weight:23.00)
Repetition.create(workoutset_id:90,  is_complete: true, quantity:9, weight:23.00)
Repetition.create(workoutset_id:90,  is_complete: true, quantity:10, weight:23.00)
Repetition.create(workoutset_id:91,  is_complete: true, quantity:8, weight:12.00)
Repetition.create(workoutset_id:98,  is_complete: true, quantity:10, weight:80.00)
Repetition.create(workoutset_id:98,  is_complete: true, quantity:6, weight:80.00)
Repetition.create(workoutset_id:98,  is_complete: true, quantity:4, weight:75.00)
Repetition.create(workoutset_id:98,  is_complete: true, quantity:6, weight:75.00)
Repetition.create(workoutset_id:98,  is_complete: true, quantity:4, weight:70.00)
Repetition.create(workoutset_id:99,  is_complete: true, quantity:9, weight:60.00)
Repetition.create(workoutset_id:99,  is_complete: true, quantity:9, weight:60.00)
Repetition.create(workoutset_id:99,  is_complete: true, quantity:6, weight:60.00)
Repetition.create(workoutset_id:99,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:100,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:100,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:100,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:100,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:101,  is_complete: true, quantity:10, weight:27.00)
Repetition.create(workoutset_id:101,  is_complete: true, quantity:10, weight:32.00)
Repetition.create(workoutset_id:101,  is_complete: true, quantity:10, weight:27.00)
Repetition.create(workoutset_id:101,  is_complete: true, quantity:10, weight:32.00)
Repetition.create(workoutset_id:102,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:102,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:102,  is_complete: true, quantity:9, weight:20.00)
Repetition.create(workoutset_id:102,  is_complete: true, quantity:9, weight:20.00)
Repetition.create(workoutset_id:103,  is_complete: true, quantity:10, weight:64.00)
Repetition.create(workoutset_id:103,  is_complete: true, quantity:10, weight:68.00)
Repetition.create(workoutset_id:103,  is_complete: true, quantity:10, weight:68.00)
Repetition.create(workoutset_id:103,  is_complete: true, quantity:10, weight:73.00)
Repetition.create(workoutset_id:104,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:104,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:104,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:104,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:105,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:105,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:106,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:106,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:105,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:106,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:106,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:105,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:107,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:107,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:107,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:108,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:108,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:108,  is_complete: true, quantity:8, weight:75.00)
Repetition.create(workoutset_id:108,  is_complete: true, quantity:2, weight:70.00)
Repetition.create(workoutset_id:108,  is_complete: true, quantity:5, weight:75.00)
Repetition.create(workoutset_id:108,  is_complete: true, quantity:5, weight:70.00)
Repetition.create(workoutset_id:109,  is_complete: true, quantity:10, weight:22.00)
Repetition.create(workoutset_id:109,  is_complete: true, quantity:10, weight:22.00)
Repetition.create(workoutset_id:109,  is_complete: true, quantity:10, weight:22.00)
Repetition.create(workoutset_id:109,  is_complete: true, quantity:10, weight:22.00)
Repetition.create(workoutset_id:110,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:110,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:110,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:110,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:111,  is_complete: true, quantity:10, weight:49.00)
Repetition.create(workoutset_id:112,  is_complete: true, quantity:9, weight:0.00)
Repetition.create(workoutset_id:112,  is_complete: true, quantity:9, weight:0.00)
Repetition.create(workoutset_id:111,  is_complete: true, quantity:9, weight:49.00)
Repetition.create(workoutset_id:111,  is_complete: true, quantity:9, weight:49.00)
Repetition.create(workoutset_id:112,  is_complete: true, quantity:9, weight:0.00)
Repetition.create(workoutset_id:112,  is_complete: true, quantity:5, weight:0.00)
Repetition.create(workoutset_id:111,  is_complete: true, quantity:9, weight:49.00)
Repetition.create(workoutset_id:115,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:115,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:115,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:115,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:116,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:116,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:116,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:116,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:117,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:118,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:117,  is_complete: true, quantity:10, weight:45.00)
Repetition.create(workoutset_id:118,  is_complete: true, quantity:10, weight:45.00)
Repetition.create(workoutset_id:118,  is_complete: true, quantity:9, weight:41.00)
Repetition.create(workoutset_id:117,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:119,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:119,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:119,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:120,  is_complete: true, quantity:10, weight:25.00)
Repetition.create(workoutset_id:120,  is_complete: true, quantity:10, weight:30.00)
Repetition.create(workoutset_id:121,  is_complete: true, quantity:10, weight:70.00)
Repetition.create(workoutset_id:121,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:121,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:121,  is_complete: true, quantity:9, weight:80.00)
Repetition.create(workoutset_id:122,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:123,  is_complete: true, quantity:10, weight:16.00)
Repetition.create(workoutset_id:123,  is_complete: true, quantity:10, weight:16.00)
Repetition.create(workoutset_id:122,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:122,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:123,  is_complete: true, quantity:10, weight:16.00)
Repetition.create(workoutset_id:123,  is_complete: true, quantity:10, weight:16.00)
Repetition.create(workoutset_id:122,  is_complete: true, quantity:8, weight:60.00)
Repetition.create(workoutset_id:124,  is_complete: true, quantity:10, weight:30.00)
Repetition.create(workoutset_id:124,  is_complete: true, quantity:10, weight:30.00)
Repetition.create(workoutset_id:124,  is_complete: true, quantity:10, weight:30.00)
Repetition.create(workoutset_id:124,  is_complete: true, quantity:8, weight:30.00)
Repetition.create(workoutset_id:125,  is_complete: true, quantity:10, weight:27.00)
Repetition.create(workoutset_id:125,  is_complete: true, quantity:10, weight:27.00)
Repetition.create(workoutset_id:126,  is_complete: true, quantity:10, weight:68.00)
Repetition.create(workoutset_id:126,  is_complete: true, quantity:10, weight:77.00)
Repetition.create(workoutset_id:126,  is_complete: true, quantity:8, weight:77.00)
Repetition.create(workoutset_id:126,  is_complete: true, quantity:10, weight:73.00)
Repetition.create(workoutset_id:127,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:128,  is_complete: true, quantity:15, weight:0.00)
Repetition.create(workoutset_id:128,  is_complete: true, quantity:15, weight:0.00)
Repetition.create(workoutset_id:128,  is_complete: true, quantity:15, weight:0.00)
Repetition.create(workoutset_id:127,  is_complete: true, quantity:10, weight:12.00)
Repetition.create(workoutset_id:127,  is_complete: true, quantity:10, weight:12.00)
Repetition.create(workoutset_id:127,  is_complete: true, quantity:10, weight:12.00)
Repetition.create(workoutset_id:129,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:129,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:132,  is_complete: true, quantity:10, weight:40.00)
Repetition.create(workoutset_id:132,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:133,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:133,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:133,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:132,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:133,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:132,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:134,  is_complete: true, quantity:10, weight:30.00)
Repetition.create(workoutset_id:134,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:134,  is_complete: true, quantity:10, weight:30.00)
Repetition.create(workoutset_id:134,  is_complete: true, quantity:10, weight:30.00)
Repetition.create(workoutset_id:135,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:135,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:135,  is_complete: true, quantity:10, weight:64.00)
Repetition.create(workoutset_id:135,  is_complete: true, quantity:10, weight:68.00)
Repetition.create(workoutset_id:136,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:136,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:136,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:136,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:137,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:137,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:137,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:137,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:138,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:138,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:138,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:138,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:139,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:139,  is_complete: true, quantity:9, weight:0.00)
Repetition.create(workoutset_id:140,  is_complete: true, quantity:10, weight:49.00)
Repetition.create(workoutset_id:140,  is_complete: true, quantity:9, weight:49.00)
Repetition.create(workoutset_id:139,  is_complete: true, quantity:5, weight:0.00)
Repetition.create(workoutset_id:140,  is_complete: true, quantity:9, weight:49.00)
Repetition.create(workoutset_id:139,  is_complete: true, quantity:6, weight:0.00)
Repetition.create(workoutset_id:140,  is_complete: true, quantity:9, weight:49.00)
Repetition.create(workoutset_id:141,  is_complete: true, quantity:10, weight:22.00)
Repetition.create(workoutset_id:141,  is_complete: true, quantity:10, weight:22.00)
Repetition.create(workoutset_id:141,  is_complete: true, quantity:10, weight:22.00)
Repetition.create(workoutset_id:141,  is_complete: true, quantity:10, weight:22.00)
Repetition.create(workoutset_id:142,  is_complete: true, quantity:10, weight:40.00)
Repetition.create(workoutset_id:142,  is_complete: true, quantity:10, weight:40.00)
Repetition.create(workoutset_id:142,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:142,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:145,  is_complete: true, quantity:10, weight:70.00)
Repetition.create(workoutset_id:145,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:145,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:145,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:146,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:147,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:147,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:146,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:146,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:147,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:147,  is_complete: true, quantity:10, weight:16.00)
Repetition.create(workoutset_id:146,  is_complete: true, quantity:8, weight:60.00)
Repetition.create(workoutset_id:148,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:148,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:148,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:148,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:149,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:149,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:149,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:150,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:150,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:151,  is_complete: true, quantity:10, weight:4.00)
Repetition.create(workoutset_id:151,  is_complete: true, quantity:10, weight:4.00)
Repetition.create(workoutset_id:151,  is_complete: true, quantity:10, weight:4.00)
Repetition.create(workoutset_id:150,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:150,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:151,  is_complete: true, quantity:10, weight:4.00)
Repetition.create(workoutset_id:152,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:153,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:152,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:153,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:152,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:153,  is_complete: true, quantity:9, weight:41.00)
Repetition.create(workoutset_id:154,  is_complete: true, quantity:10, weight:45.00)
Repetition.create(workoutset_id:154,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:154,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:155,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:155,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:155,  is_complete: true, quantity:10, weight:70.00)
Repetition.create(workoutset_id:155,  is_complete: true, quantity:10, weight:70.00)
Repetition.create(workoutset_id:156,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:156,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:156,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:156,  is_complete: true, quantity:8, weight:55.00)
Repetition.create(workoutset_id:157,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:157,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:157,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:157,  is_complete: true, quantity:8, weight:35.00)
Repetition.create(workoutset_id:158,  is_complete: true, quantity:10, weight:12.00)
Repetition.create(workoutset_id:158,  is_complete: true, quantity:10, weight:12.00)
Repetition.create(workoutset_id:159,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:159,  is_complete: true, quantity:10, weight:64.00)
Repetition.create(workoutset_id:159,  is_complete: true, quantity:10, weight:64.00)
Repetition.create(workoutset_id:158,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:160,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:160,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:160,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:160,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:161,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:161,  is_complete: true, quantity:10, weight:65.00)
Repetition.create(workoutset_id:161,  is_complete: true, quantity:10, weight:65.00)
Repetition.create(workoutset_id:161,  is_complete: true, quantity:8, weight:65.00)
Repetition.create(workoutset_id:161,  is_complete: true, quantity:3, weight:60.00)
Repetition.create(workoutset_id:162,  is_complete: true, quantity:10, weight:22.00)
Repetition.create(workoutset_id:162,  is_complete: true, quantity:10, weight:22.00)
Repetition.create(workoutset_id:162,  is_complete: true, quantity:10, weight:22.00)
Repetition.create(workoutset_id:162,  is_complete: true, quantity:10, weight:22.00)
Repetition.create(workoutset_id:163,  is_complete: true, quantity:10, weight:40.00)
Repetition.create(workoutset_id:163,  is_complete: true, quantity:10, weight:40.00)
Repetition.create(workoutset_id:163,  is_complete: true, quantity:10, weight:40.00)
Repetition.create(workoutset_id:163,  is_complete: true, quantity:10, weight:40.00)
Repetition.create(workoutset_id:164,  is_complete: true, quantity:9, weight:0.00)
Repetition.create(workoutset_id:164,  is_complete: true, quantity:9, weight:0.00)
Repetition.create(workoutset_id:164,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:164,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:165,  is_complete: true, quantity:15, weight:0.00)
Repetition.create(workoutset_id:165,  is_complete: true, quantity:15, weight:0.00)
Repetition.create(workoutset_id:165,  is_complete: true, quantity:12, weight:0.00)
Repetition.create(workoutset_id:165,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:166,  is_complete: true, quantity:10, weight:18.00)
Repetition.create(workoutset_id:166,  is_complete: true, quantity:9, weight:20.00)
Repetition.create(workoutset_id:166,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:166,  is_complete: true, quantity:8, weight:20.00)
Repetition.create(workoutset_id:166,  is_complete: true, quantity:2, weight:18.00)
Repetition.create(workoutset_id:167,  is_complete: true, quantity:10, weight:30.00)
Repetition.create(workoutset_id:167,  is_complete: true, quantity:10, weight:30.00)
Repetition.create(workoutset_id:167,  is_complete: true, quantity:10, weight:30.00)
Repetition.create(workoutset_id:168,  is_complete: true, quantity:10, weight:12.00)
Repetition.create(workoutset_id:168,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:167,  is_complete: true, quantity:10, weight:30.00)
Repetition.create(workoutset_id:168,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:169,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:169,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:168,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:169,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:169,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:170,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:170,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:170,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:170,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:171,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:171,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:171,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:171,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:172,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:172,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:172,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:172,  is_complete: true, quantity:8, weight:55.00)
Repetition.create(workoutset_id:173,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:174,  is_complete: true, quantity:10, weight:12.00)
Repetition.create(workoutset_id:173,  is_complete: true, quantity:10, weight:65.00)
Repetition.create(workoutset_id:174,  is_complete: true, quantity:10, weight:12.00)
Repetition.create(workoutset_id:174,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:173,  is_complete: true, quantity:10, weight:65.00)
Repetition.create(workoutset_id:173,  is_complete: true, quantity:10, weight:65.00)
Repetition.create(workoutset_id:174,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:175,  is_complete: true, quantity:10, weight:27.00)
Repetition.create(workoutset_id:175,  is_complete: true, quantity:10, weight:27.00)
Repetition.create(workoutset_id:175,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:175,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:176,  is_complete: true, quantity:10, weight:12.00)
Repetition.create(workoutset_id:176,  is_complete: true, quantity:10, weight:12.00)
Repetition.create(workoutset_id:176,  is_complete: true, quantity:10, weight:12.00)
Repetition.create(workoutset_id:176,  is_complete: true, quantity:10, weight:12.00)
Repetition.create(workoutset_id:177,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:178,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:177,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:178,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:177,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:177,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:178,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:178,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:179,  is_complete: true, quantity:19, weight:0.00)
Repetition.create(workoutset_id:179,  is_complete: true, quantity:15, weight:0.00)
Repetition.create(workoutset_id:179,  is_complete: true, quantity:15, weight:0.00)
Repetition.create(workoutset_id:182,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:182,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:182,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:182,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:183,  is_complete: true, quantity:10, weight:54.00)
Repetition.create(workoutset_id:183,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:183,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:183,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:184,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:185,  is_complete: true, quantity:8, weight:9.00)
Repetition.create(workoutset_id:185,  is_complete: true, quantity:9, weight:14.00)
Repetition.create(workoutset_id:184,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:184,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:185,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:185,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:184,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:186,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:186,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:186,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:187,  is_complete: true, quantity:10, weight:40.00)
Repetition.create(workoutset_id:188,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:187,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:188,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:187,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:188,  is_complete: true, quantity:9, weight:41.00)
Repetition.create(workoutset_id:190,  is_complete: true, quantity:10, weight:18.00)
Repetition.create(workoutset_id:190,  is_complete: true, quantity:10, weight:18.00)
Repetition.create(workoutset_id:190,  is_complete: true, quantity:10, weight:18.00)
Repetition.create(workoutset_id:190,  is_complete: true, quantity:10, weight:18.00)
Repetition.create(workoutset_id:191,  is_complete: true, quantity:10, weight:12.00)
Repetition.create(workoutset_id:191,  is_complete: true, quantity:10, weight:12.00)
Repetition.create(workoutset_id:191,  is_complete: true, quantity:10, weight:12.00)
Repetition.create(workoutset_id:191,  is_complete: true, quantity:10, weight:12.00)
Repetition.create(workoutset_id:192,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:192,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:192,  is_complete: true, quantity:10, weight:4.00)
Repetition.create(workoutset_id:192,  is_complete: true, quantity:10, weight:4.00)
Repetition.create(workoutset_id:193,  is_complete: true, quantity:10, weight:25.00)
Repetition.create(workoutset_id:193,  is_complete: true, quantity:10, weight:25.00)
Repetition.create(workoutset_id:193,  is_complete: true, quantity:10, weight:25.00)
Repetition.create(workoutset_id:193,  is_complete: true, quantity:10, weight:27.50)
Repetition.create(workoutset_id:194,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:194,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:194,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:194,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:195,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:195,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:195,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:195,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:196,  is_complete: true, quantity:10, weight:45.00)
Repetition.create(workoutset_id:196,  is_complete: true, quantity:10, weight:49.00)
Repetition.create(workoutset_id:196,  is_complete: true, quantity:10, weight:49.00)
Repetition.create(workoutset_id:196,  is_complete: true, quantity:10, weight:49.00)
Repetition.create(workoutset_id:197,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:197,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:197,  is_complete: true, quantity:8, weight:0.00)
Repetition.create(workoutset_id:197,  is_complete: true, quantity:6, weight:0.00)
Repetition.create(workoutset_id:198,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:198,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:198,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:198,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:199,  is_complete: true, quantity:10, weight:36.00)
Repetition.create(workoutset_id:199,  is_complete: true, quantity:10, weight:45.00)
Repetition.create(workoutset_id:199,  is_complete: true, quantity:10, weight:49.00)
Repetition.create(workoutset_id:199,  is_complete: true, quantity:10, weight:54.00)
Repetition.create(workoutset_id:200,  is_complete: true, quantity:8, weight:8.00)
Repetition.create(workoutset_id:200,  is_complete: true, quantity:10, weight:8.00)
Repetition.create(workoutset_id:200,  is_complete: true, quantity:9, weight:8.00)
Repetition.create(workoutset_id:200,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:201,  is_complete: true, quantity:10, weight:40.00)
Repetition.create(workoutset_id:201,  is_complete: true, quantity:10, weight:45.00)
Repetition.create(workoutset_id:201,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:202,  is_complete: true, quantity:10, weight:36.00)
Repetition.create(workoutset_id:202,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:202,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:203,  is_complete: true, quantity:10, weight:16.00)
Repetition.create(workoutset_id:203,  is_complete: true, quantity:10, weight:18.00)
Repetition.create(workoutset_id:203,  is_complete: true, quantity:10, weight:18.00)
Repetition.create(workoutset_id:203,  is_complete: true, quantity:10, weight:18.00)
Repetition.create(workoutset_id:204,  is_complete: true, quantity:10, weight:8.00)
Repetition.create(workoutset_id:204,  is_complete: true, quantity:10, weight:10.00)
Repetition.create(workoutset_id:204,  is_complete: true, quantity:10, weight:10.00)
Repetition.create(workoutset_id:204,  is_complete: true, quantity:10, weight:10.00)
Repetition.create(workoutset_id:205,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:205,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:205,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:205,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:206,  is_complete: true, quantity:10, weight:25.00)
Repetition.create(workoutset_id:206,  is_complete: true, quantity:10, weight:25.00)
Repetition.create(workoutset_id:206,  is_complete: true, quantity:10, weight:25.00)
Repetition.create(workoutset_id:206,  is_complete: true, quantity:10, weight:25.00)
Repetition.create(workoutset_id:207,  is_complete: true, quantity:10, weight:16.00)
Repetition.create(workoutset_id:207,  is_complete: true, quantity:10, weight:16.00)
Repetition.create(workoutset_id:207,  is_complete: true, quantity:10, weight:16.00)
Repetition.create(workoutset_id:207,  is_complete: true, quantity:10, weight:16.00)
Repetition.create(workoutset_id:208,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:208,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:208,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:208,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:209,  is_complete: true, quantity:10, weight:16.00)
Repetition.create(workoutset_id:209,  is_complete: true, quantity:10, weight:16.00)
Repetition.create(workoutset_id:209,  is_complete: true, quantity:10, weight:16.00)
Repetition.create(workoutset_id:209,  is_complete: true, quantity:10, weight:16.00)
Repetition.create(workoutset_id:210,  is_complete: true, quantity:10, weight:10.00)
Repetition.create(workoutset_id:210,  is_complete: true, quantity:10, weight:10.00)
Repetition.create(workoutset_id:210,  is_complete: true, quantity:10, weight:10.00)
Repetition.create(workoutset_id:210,  is_complete: true, quantity:10, weight:10.00)
Repetition.create(workoutset_id:211,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:211,  is_complete: true, quantity:10, weight:4.00)
Repetition.create(workoutset_id:211,  is_complete: true, quantity:10, weight:4.00)
Repetition.create(workoutset_id:211,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:212,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:212,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:212,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:212,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:213,  is_complete: true, quantity:10, weight:40.00)
Repetition.create(workoutset_id:213,  is_complete: true, quantity:10, weight:40.00)
Repetition.create(workoutset_id:213,  is_complete: true, quantity:10, weight:40.00)
Repetition.create(workoutset_id:213,  is_complete: true, quantity:10, weight:40.00)
Repetition.create(workoutset_id:1,  is_complete: true, quantity:15, weight:12.00)
Repetition.create(workoutset_id:1,  is_complete: true, quantity:15, weight:12.00)
Repetition.create(workoutset_id:1,  is_complete: true, quantity:15, weight:12.00)
Repetition.create(workoutset_id:1,  is_complete: true, quantity:15, weight:12.00)
Repetition.create(workoutset_id:2,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:2,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:2,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:2,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:3,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:3,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:3,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:3,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:4,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:4,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:4,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:4,  is_complete: true, quantity:10, weight:75.00)
Repetition.create(workoutset_id:5,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:5,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:5,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:5,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:6,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:6,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:6,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:6,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:7,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:7,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:7,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:7,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:8,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:8,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:8,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:8,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:9,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:9,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:9,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:9,  is_complete: true, quantity:10, weight:6.00)
Repetition.create(workoutset_id:10,  is_complete: true, quantity:10, weight:27.00)
Repetition.create(workoutset_id:10,  is_complete: true, quantity:10, weight:27.00)
Repetition.create(workoutset_id:10,  is_complete: true, quantity:10, weight:27.00)
Repetition.create(workoutset_id:10,  is_complete: true, quantity:10, weight:27.00)
Repetition.create(workoutset_id:11,  is_complete: true, quantity:10, weight:27.00)
Repetition.create(workoutset_id:11,  is_complete: true, quantity:10, weight:27.00)
Repetition.create(workoutset_id:11,  is_complete: true, quantity:10, weight:27.00)
Repetition.create(workoutset_id:11,  is_complete: true, quantity:10, weight:27.00)
Repetition.create(workoutset_id:12,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:12,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:12,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:12,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:13,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:13,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:13,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:13,  is_complete: true, quantity:10, weight:55.00)
Repetition.create(workoutset_id:14,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:14,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:14,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:14,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:15,  is_complete: true, quantity:10, weight:14.00)
Repetition.create(workoutset_id:15,  is_complete: true, quantity:8, weight:12.00)
Repetition.create(workoutset_id:15,  is_complete: true, quantity:10, weight:12.00)
Repetition.create(workoutset_id:15,  is_complete: true, quantity:10, weight:12.00)
Repetition.create(workoutset_id:16,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:16,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:16,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:16,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:17,  is_complete: true, quantity:10, weight:10.00)
Repetition.create(workoutset_id:17,  is_complete: true, quantity:10, weight:10.00)
Repetition.create(workoutset_id:17,  is_complete: true, quantity:10, weight:10.00)
Repetition.create(workoutset_id:17,  is_complete: true, quantity:10, weight:10.00)
Repetition.create(workoutset_id:18,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:18,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:18,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:18,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:19,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:19,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:19,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:19,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:20,  is_complete: true, quantity:10, weight:16.00)
Repetition.create(workoutset_id:20,  is_complete: true, quantity:10, weight:16.00)
Repetition.create(workoutset_id:20,  is_complete: true, quantity:10, weight:16.00)
Repetition.create(workoutset_id:20,  is_complete: true, quantity:10, weight:16.00)
Repetition.create(workoutset_id:21,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:21,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:21,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:21,  is_complete: true, quantity:10, weight:60.00)
Repetition.create(workoutset_id:22,  is_complete: true, quantity:10, weight:24.00)
Repetition.create(workoutset_id:22,  is_complete: true, quantity:10, weight:24.00)
Repetition.create(workoutset_id:22,  is_complete: true, quantity:10, weight:24.00)
Repetition.create(workoutset_id:22,  is_complete: true, quantity:10, weight:24.00)
Repetition.create(workoutset_id:23,  is_complete: true, quantity:10, weight:54.00)
Repetition.create(workoutset_id:23,  is_complete: true, quantity:10, weight:54.00)
Repetition.create(workoutset_id:23,  is_complete: true, quantity:10, weight:54.00)
Repetition.create(workoutset_id:23,  is_complete: true, quantity:10, weight:54.00)
Repetition.create(workoutset_id:24,  is_complete: true, quantity:10, weight:54.00)
Repetition.create(workoutset_id:24,  is_complete: true, quantity:10, weight:54.00)
Repetition.create(workoutset_id:24,  is_complete: true, quantity:10, weight:54.00)
Repetition.create(workoutset_id:24,  is_complete: true, quantity:10, weight:54.00)
Repetition.create(workoutset_id:25,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:25,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:25,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:25,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:26,  is_complete: true, quantity:10, weight:70.00)
Repetition.create(workoutset_id:26,  is_complete: true, quantity:10, weight:70.00)
Repetition.create(workoutset_id:26,  is_complete: true, quantity:10, weight:70.00)
Repetition.create(workoutset_id:26,  is_complete: true, quantity:10, weight:70.00)
Repetition.create(workoutset_id:27,  is_complete: true, quantity:10, weight:25.00)
Repetition.create(workoutset_id:27,  is_complete: true, quantity:10, weight:25.00)
Repetition.create(workoutset_id:27,  is_complete: true, quantity:10, weight:25.00)
Repetition.create(workoutset_id:27,  is_complete: true, quantity:10, weight:25.00)
Repetition.create(workoutset_id:28,  is_complete: true, quantity:10, weight:73.00)
Repetition.create(workoutset_id:28,  is_complete: true, quantity:10, weight:73.00)
Repetition.create(workoutset_id:28,  is_complete: true, quantity:10, weight:73.00)
Repetition.create(workoutset_id:28,  is_complete: true, quantity:10, weight:73.00)
Repetition.create(workoutset_id:29,  is_complete: true, quantity:10, weight:64.00)
Repetition.create(workoutset_id:29,  is_complete: true, quantity:10, weight:64.00)
Repetition.create(workoutset_id:29,  is_complete: true, quantity:10, weight:64.00)
Repetition.create(workoutset_id:29,  is_complete: true, quantity:10, weight:64.00)
Repetition.create(workoutset_id:30,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:30,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:30,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:30,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:31,  is_complete: true, quantity:8, weight:8.00)
Repetition.create(workoutset_id:31,  is_complete: true, quantity:10, weight:8.00)
Repetition.create(workoutset_id:31,  is_complete: true, quantity:10, weight:8.00)
Repetition.create(workoutset_id:31,  is_complete: true, quantity:8, weight:8.00)
Repetition.create(workoutset_id:32,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:32,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:32,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:32,  is_complete: true, quantity:10, weight:59.00)
Repetition.create(workoutset_id:33,  is_complete: true, quantity:10, weight:23.00)
Repetition.create(workoutset_id:33,  is_complete: true, quantity:10, weight:23.00)
Repetition.create(workoutset_id:33,  is_complete: true, quantity:10, weight:23.00)
Repetition.create(workoutset_id:33,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:34,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:34,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:34,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:34,  is_complete: true, quantity:10, weight:41.00)
Repetition.create(workoutset_id:35,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:35,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:35,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:35,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:36,  is_complete: true, quantity:9, weight:0.00)
Repetition.create(workoutset_id:36,  is_complete: true, quantity:9, weight:0.00)
Repetition.create(workoutset_id:36,  is_complete: true, quantity:9, weight:0.00)
Repetition.create(workoutset_id:36,  is_complete: true, quantity:5, weight:0.00)
Repetition.create(workoutset_id:37,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:37,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:37,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:37,  is_complete: true, quantity:10, weight:35.00)
Repetition.create(workoutset_id:38,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:38,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:38,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:38,  is_complete: true, quantity:10, weight:50.00)
Repetition.create(workoutset_id:39,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:39,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:39,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:39,  is_complete: true, quantity:10, weight:20.00)
Repetition.create(workoutset_id:40,  is_complete: true, quantity:10, weight:77.00)
Repetition.create(workoutset_id:40,  is_complete: true, quantity:10, weight:77.00)
Repetition.create(workoutset_id:40,  is_complete: true, quantity:10, weight:77.00)
Repetition.create(workoutset_id:40,  is_complete: true, quantity:10, weight:77.00)
Repetition.create(workoutset_id:41,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:41,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:41,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:41,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:42,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:42,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:42,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:42,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:43,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:43,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:43,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:43,  is_complete: true, quantity:10, weight:0.00)
Repetition.create(workoutset_id:44,  is_complete: true, quantity:10, weight:24.00)
Repetition.create(workoutset_id:44,  is_complete: true, quantity:10, weight:24.00)
Repetition.create(workoutset_id:44,  is_complete: true, quantity:10, weight:24.00)
Repetition.create(workoutset_id:44,  is_complete: true, quantity:10, weight:24.00)
