# PROFIL
profile_coach = Profile.create(first_name: "Coach", last_name: "Family Name", role: "Coach" )
user_coach = User.create(email: "coach@gmail.com", password: "password", profile: profile_coach)

profile_adrien = Profile.create(first_name: "Adrien", last_name: "Cassan", role: "Athlete")
user_adrien = User.create(email: "adrien.cassan@gmail.com", password: "password", profile: profile_adrien)

profile_coach = Profile.create(first_name: "Mamadou", last_name: "Coach", role: "Coach" )
user_coach = User.create(email: "mamadou@gmail.com", password: "password", profile: profile_coach)


# RESULT
result1 = Result.new(profile: profile_adrien, date: "2017-09-12", weight: 76.1, fatmass: 15)
result1.remote_selfie_url = "http://res.cloudinary.com/duojdxafe/image/upload/v1536851762/2017-09-12.jpg"
result1.save!

result2 = Result.new(profile: profile_adrien, date: "2018-04-03", weight: 75, fatmass: 13.6)
result2.remote_selfie_url = "http://res.cloudinary.com/duojdxafe/image/upload/v1536851764/2018-04-03.jpg"
result2.save!

result3 = Result.new(profile: profile_adrien, date: "2018-06-18", weight: 74.6, fatmass: 14)
result3.remote_selfie_url = "http://res.cloudinary.com/duojdxafe/image/upload/v1536851762/2018-06-18.jpg"
result3.save!

result4 = Result.new(profile: profile_adrien, date: "2018-08-26", weight: 78.7, fatmass: 10.6)
result4.remote_selfie_url = "http://res.cloudinary.com/duojdxafe/image/upload/v1536851763/2018-08-26.jpg"
result4.save!

# EXERCICES
Exercice.create(name: 'Back Extensions', nameEN: 'Back Extensions')
Exercice.create(name: 'Barbell Back Presses', nameEN: 'Barbell Back Presses')
Exercice.create(name: 'Barbell Bench Presses', nameEN: 'Barbell Bench Presses')
Exercice.create(name: 'Barbell Curls', nameEN: 'Barbell Curls')
Exercice.create(name: 'Barbell Deadlifts', nameEN: 'Barbell Deadlifts')
Exercice.create(name: 'Barbell Rows', nameEN: 'Barbell Rows')
Exercice.create(name: 'Bent-Over Dumbbell Lateral Raises', nameEN: 'Bent-Over Dumbbell Lateral Raises')
Exercice.create(name: 'Cable Flys', nameEN: 'Cable Flys')
Exercice.create(name: 'Chin-Ups', nameEN: 'Chin-Ups')
Exercice.create(name: 'Close-Grip Barbell Bench Presses', nameEN: 'Close-Grip Barbell Bench Presses')
Exercice.create(name: 'Close-Grip Lat Pull-Downs', nameEN: 'Close-Grip Lat Pull-Downs')
Exercice.create(name: 'Concentration Curls', nameEN: 'Concentration Curls')
Exercice.create(name: 'Developpe Militaire', nameEN: 'Developpe Militaire')
Exercice.create(name: 'Dumbbell Front Raises', nameEN: 'Dumbbell Front Raises')
Exercice.create(name: 'Dumbbell Shrugs', nameEN: 'Dumbbell Shrugs')
Exercice.create(name: 'Extensions triceps Poulie Reverse', nameEN: 'Extensions triceps Poulie Reverse')
Exercice.create(name: 'Hammer Curls', nameEN: 'Hammer Curls')
Exercice.create(name: 'Incline Barbell Bench Presses', nameEN: 'Incline Barbell Bench Presses')
Exercice.create(name: 'Incline Dumbbell Flys', nameEN: 'Incline Dumbbell Flys')
Exercice.create(name: 'Lat Pull-Downs', nameEN: 'Lat Pull-Downs')
Exercice.create(name: 'Leg Extensions', nameEN: 'Leg Extensions')
Exercice.create(name: 'Leg Presses', nameEN: 'Leg Presses')
Exercice.create(name: 'Lying Barbell Triceps Extensions', nameEN: 'Lying Barbell Triceps Extensions')
Exercice.create(name: 'Machine Bench Presses', nameEN: 'Machine Bench Presses')
Exercice.create(name: 'Machine Flys', nameEN: 'Machine Flys')
Exercice.create(name: 'Machine Presses', nameEN: 'Machine Presses')
Exercice.create(name: 'Parallel Bar Dips', nameEN: 'Parallel Bar Dips')
Exercice.create(name: 'Poulie Verticale', nameEN: 'Poulie Verticale')
Exercice.create(name: 'Poulis Basse', nameEN: 'Poulis Basse')
Exercice.create(name: 'Push-Downs', nameEN: 'Push-Downs')
Exercice.create(name: 'Push-Ups', nameEN: 'Push-Ups')
Exercice.create(name: 'Reverse Chin-Ups', nameEN: 'Reverse Chin-Ups')
Exercice.create(name: 'Rowing vertical', nameEN: 'Rowing vertical')
Exercice.create(name: 'Smith Machine Squats', nameEN: 'Smith Machine Squats')
Exercice.create(name: 'Swing au Kettle bell', nameEN: 'Swing au Kettle bell')
Exercice.create(name: 'Tirage horizontal', nameEN: 'Tirage horizontal')
Exercice.create(name: 'TRX Biceps', nameEN: 'TRX Biceps')
Exercice.create(name: 'TRX calins', nameEN: 'TRX calins')
Exercice.create(name: 'TRX Push-up Large', nameEN: 'TRX Push-up Large')
Exercice.create(name: 'Walking Lunges', nameEN: 'Walking Lunges')
Exercice.create(name: 'Flexions des jambes', nameEN: 'Flexions des jambes')
Exercice.create(name: 'Extensions des fessiers', nameEN: 'Extensions des fessiers')
Exercice.create(name: 'Barbell Squat', nameEN: 'Barbell Squat')
Exercice.create(name: 'Curl Debout à la poulie', nameEN: 'Curl Debout à la poulie')


Workout.create(date: '1900-01-01', name: 'Dos & Triceps', is_program: true, profile_id: 2, program_id:0)
Workout.create(date: '1900-01-01', name: 'Epaules & Trapezes', is_program: true, profile_id: 2, program_id:0)
Workout.create(date: '1900-01-01', name: 'Pectoraux & Biceps', is_program: true, profile_id: 2, program_id:0)
Workout.create(date: '1900-01-01', name: 'Pectoraux & Dos', is_program: true, profile_id: 2, program_id:0)
Workout.create(date: '1900-01-01', name: 'Pectoraux & Jambes', is_program: true, profile_id: 2, program_id:0)
Workout.create(date: '2018-09-14', name: 'Pectoraux & Biceps', is_program: false, profile_id: 2, program_id:3)
Workout.create(date: '2018-09-09', name: 'Pectoraux & Jambes', is_program: false, profile_id: 2, program_id:5)
Workout.create(date: '2018-09-08', name: 'Epaules & Trapezes', is_program: false, profile_id: 2, program_id:2)
Workout.create(date: '2018-09-04', name: 'Epaules & Trapezes', is_program: false, profile_id: 2, program_id:2)
Workout.create(date: '2018-09-01', name: 'Pectoraux & Dos', is_program: false, profile_id: 2, program_id:4)
Workout.create(date: '2018-08-30', name: 'Pectoraux & Biceps', is_program: false, profile_id: 2, program_id:3)
Workout.create(date: '2018-08-26', name: 'Pectoraux & Biceps', is_program: false, profile_id: 2, program_id:3)
Workout.create(date: '2018-08-23', name: 'Dos & Triceps', is_program: false, profile_id: 2, program_id:1)
Workout.create(date: '2018-08-21', name: 'Pectoraux & Biceps', is_program: false, profile_id: 2, program_id:3)
Workout.create(date: '2018-08-18', name: 'Pectoraux & Biceps', is_program: false, profile_id: 2, program_id:3)
Workout.create(date: '2018-08-18', name: 'Pectoraux & Jambes', is_program: false, profile_id: 2, program_id:5)
Workout.create(date: '2018-08-17', name: 'Epaules & Trapezes', is_program: false, profile_id: 2, program_id:2)
Workout.create(date: '2018-08-16', name: 'Pectoraux & Dos', is_program: false, profile_id: 2, program_id:4)
Workout.create(date: '2018-08-14', name: 'Dos & Triceps', is_program: false, profile_id: 2, program_id:1)
Workout.create(date: '2018-08-11', name: 'Pectoraux & Biceps', is_program: false, profile_id: 2, program_id:3)
Workout.create(date: '2018-08-10', name: 'Epaules & Trapezes', is_program: false, profile_id: 2, program_id:2)
Workout.create(date: '2018-08-06', name: 'Pectoraux & Dos', is_program: false, profile_id: 2, program_id:4)
Workout.create(date: '2018-08-03', name: 'Pectoraux & Biceps', is_program: false, profile_id: 2, program_id:3)
Workout.create(date: '2018-08-01', name: 'Dos & Triceps', is_program: false, profile_id: 2, program_id:1)
Workout.create(date: '2018-07-30', name: 'Pectoraux & Biceps', is_program: false, profile_id: 2, program_id:3)
Workout.create(date: '2018-07-28', name: 'Pectoraux & Dos', is_program: false, profile_id: 2, program_id:4)
Workout.create(date: '2018-07-26', name: 'Epaules & Trapezes', is_program: false, profile_id: 2, program_id:2)
Workout.create(date: '2018-07-25', name: 'Pectoraux & Biceps', is_program: false, profile_id: 2, program_id:3)
Workout.create(date: '2018-07-23', name: 'Dos & Triceps', is_program: false, profile_id: 2, program_id:1)
Workout.create(date: '2018-07-20', name: 'Epaules & Trapezes', is_program: false, profile_id: 2, program_id:2)
Workout.create(date: '2018-07-20', name: 'Dos & Triceps', is_program: false, profile_id: 2, program_id:1)
Workout.create(date: '2018-07-17', name: 'Dos & Triceps', is_program: false, profile_id: 2, program_id:1)
Workout.create(date: '2018-07-13', name: 'Epaules & Trapezes', is_program: false, profile_id: 2, program_id:2)
Workout.create(date: '2018-06-20', name: 'Epaules & Trapezes', is_program: false, profile_id: 2, program_id:2)
Workoutset.create(workout_id: 1, exercice_id: 1)
Workoutset.create(workout_id: 2, exercice_id: 2)
Workoutset.create(workout_id: 3, exercice_id: 3)
Workoutset.create(workout_id: 4, exercice_id: 3)
Workoutset.create(workout_id: 3, exercice_id: 4)
Workoutset.create(workout_id: 1, exercice_id: 5)
Workoutset.create(workout_id: 4, exercice_id: 5)
Workoutset.create(workout_id: 4, exercice_id: 6)
Workoutset.create(workout_id: 2, exercice_id: 7)
Workoutset.create(workout_id: 3, exercice_id: 8)
Workoutset.create(workout_id: 5, exercice_id: 8)
Workoutset.create(workout_id: 1, exercice_id: 9)
Workoutset.create(workout_id: 1, exercice_id: 10)
Workoutset.create(workout_id: 1, exercice_id: 11)
Workoutset.create(workout_id: 3, exercice_id: 12)
Workoutset.create(workout_id: 2, exercice_id: 13)
Workoutset.create(workout_id: 2, exercice_id: 14)
Workoutset.create(workout_id: 2, exercice_id: 15)
Workoutset.create(workout_id: 1, exercice_id: 16)
Workoutset.create(workout_id: 3, exercice_id: 17)
Workoutset.create(workout_id: 3, exercice_id: 18)
Workoutset.create(workout_id: 4, exercice_id: 19)
Workoutset.create(workout_id: 1, exercice_id: 20)
Workoutset.create(workout_id: 4, exercice_id: 20)
Workoutset.create(workout_id: 5, exercice_id: 21)
Workoutset.create(workout_id: 5, exercice_id: 22)
Workoutset.create(workout_id: 1, exercice_id: 23)
Workoutset.create(workout_id: 3, exercice_id: 24)
Workoutset.create(workout_id: 3, exercice_id: 25)
Workoutset.create(workout_id: 2, exercice_id: 26)
Workoutset.create(workout_id: 1, exercice_id: 27)
Workoutset.create(workout_id: 1, exercice_id: 28)
Workoutset.create(workout_id: 3, exercice_id: 29)
Workoutset.create(workout_id: 1, exercice_id: 30)
Workoutset.create(workout_id: 3, exercice_id: 31)
Workoutset.create(workout_id: 4, exercice_id: 32)
Workoutset.create(workout_id: 2, exercice_id: 33)
Workoutset.create(workout_id: 5, exercice_id: 34)
Workoutset.create(workout_id: 2, exercice_id: 35)
Workoutset.create(workout_id: 2, exercice_id: 36)
Workoutset.create(workout_id: 3, exercice_id: 37)
Workoutset.create(workout_id: 3, exercice_id: 38)
Workoutset.create(workout_id: 4, exercice_id: 39)
Workoutset.create(workout_id: 5, exercice_id: 40)
Workoutset.create(workout_id: 6, exercice_id: 3)
Workoutset.create(workout_id: 6, exercice_id: 17)
Workoutset.create(workout_id: 6, exercice_id: 18)
Workoutset.create(workout_id: 6, exercice_id: 24)
Workoutset.create(workout_id: 6, exercice_id: 4)
Workoutset.create(workout_id: 7, exercice_id: 34)
Workoutset.create(workout_id: 7, exercice_id: 21)
Workoutset.create(workout_id: 7, exercice_id: 40)
Workoutset.create(workout_id: 7, exercice_id: 22)
Workoutset.create(workout_id: 8, exercice_id: 2)
Workoutset.create(workout_id: 8, exercice_id: 14)
Workoutset.create(workout_id: 8, exercice_id: 36)
Workoutset.create(workout_id: 8, exercice_id: 26)
Workoutset.create(workout_id: 8, exercice_id: 15)
Workoutset.create(workout_id: 8, exercice_id: 33)
Workoutset.create(workout_id: 8, exercice_id: 7)
Workoutset.create(workout_id: 9, exercice_id: 2)
Workoutset.create(workout_id: 9, exercice_id: 13)
Workoutset.create(workout_id: 9, exercice_id: 33)
Workoutset.create(workout_id: 9, exercice_id: 36)
Workoutset.create(workout_id: 9, exercice_id: 14)
Workoutset.create(workout_id: 10, exercice_id: 3)
Workoutset.create(workout_id: 10, exercice_id: 19)
Workoutset.create(workout_id: 11, exercice_id: 3)
Workoutset.create(workout_id: 11, exercice_id: 17)
Workoutset.create(workout_id: 11, exercice_id: 18)
Workoutset.create(workout_id: 11, exercice_id: 4)
Workoutset.create(workout_id: 11, exercice_id: 25)
Workoutset.create(workout_id: 11, exercice_id: 31)
Workoutset.create(workout_id: 12, exercice_id: 3)
Workoutset.create(workout_id: 13, exercice_id: 9)
Workoutset.create(workout_id: 13, exercice_id: 27)
Workoutset.create(workout_id: 13, exercice_id: 10)
Workoutset.create(workout_id: 13, exercice_id: 20)
Workoutset.create(workout_id: 13, exercice_id: 28)
Workoutset.create(workout_id: 13, exercice_id: 1)
Workoutset.create(workout_id: 13, exercice_id: 11)
Workoutset.create(workout_id: 14, exercice_id: 3)
Workoutset.create(workout_id: 14, exercice_id: 18)
Workoutset.create(workout_id: 14, exercice_id: 17)
Workoutset.create(workout_id: 14, exercice_id: 4)
Workoutset.create(workout_id: 14, exercice_id: 29)
Workoutset.create(workout_id: 14, exercice_id: 12)
Workoutset.create(workout_id: 15, exercice_id: 3)
Workoutset.create(workout_id: 15, exercice_id: 18)
Workoutset.create(workout_id: 16, exercice_id: 34)
Workoutset.create(workout_id: 16, exercice_id: 8)
Workoutset.create(workout_id: 17, exercice_id: 13)
Workoutset.create(workout_id: 17, exercice_id: 36)
Workoutset.create(workout_id: 17, exercice_id: 33)
Workoutset.create(workout_id: 17, exercice_id: 14)
Workoutset.create(workout_id: 17, exercice_id: 15)
Workoutset.create(workout_id: 17, exercice_id: 7)
Workoutset.create(workout_id: 18, exercice_id: 3)
Workoutset.create(workout_id: 18, exercice_id: 19)
Workoutset.create(workout_id: 18, exercice_id: 6)
Workoutset.create(workout_id: 18, exercice_id: 20)
Workoutset.create(workout_id: 18, exercice_id: 32)
Workoutset.create(workout_id: 19, exercice_id: 5)
Workoutset.create(workout_id: 19, exercice_id: 11)
Workoutset.create(workout_id: 19, exercice_id: 30)
Workoutset.create(workout_id: 19, exercice_id: 16)
Workoutset.create(workout_id: 19, exercice_id: 10)
Workoutset.create(workout_id: 19, exercice_id: 23)
Workoutset.create(workout_id: 20, exercice_id: 3)
Workoutset.create(workout_id: 20, exercice_id: 18)
Workoutset.create(workout_id: 20, exercice_id: 17)
Workoutset.create(workout_id: 20, exercice_id: 4)
Workoutset.create(workout_id: 20, exercice_id: 8)
Workoutset.create(workout_id: 20, exercice_id: 24)
Workoutset.create(workout_id: 20, exercice_id: 12)
Workoutset.create(workout_id: 20, exercice_id: 31)
Workoutset.create(workout_id: 20, exercice_id: 38)
Workoutset.create(workout_id: 21, exercice_id: 2)
Workoutset.create(workout_id: 21, exercice_id: 14)
Workoutset.create(workout_id: 21, exercice_id: 33)
Workoutset.create(workout_id: 21, exercice_id: 36)
Workoutset.create(workout_id: 21, exercice_id: 15)
Workoutset.create(workout_id: 21, exercice_id: 26)
Workoutset.create(workout_id: 22, exercice_id: 3)
Workoutset.create(workout_id: 22, exercice_id: 32)
Workoutset.create(workout_id: 22, exercice_id: 20)
Workoutset.create(workout_id: 22, exercice_id: 19)
Workoutset.create(workout_id: 22, exercice_id: 6)
Workoutset.create(workout_id: 23, exercice_id: 3)
Workoutset.create(workout_id: 23, exercice_id: 18)
Workoutset.create(workout_id: 23, exercice_id: 17)
Workoutset.create(workout_id: 24, exercice_id: 5)
Workoutset.create(workout_id: 24, exercice_id: 10)
Workoutset.create(workout_id: 24, exercice_id: 9)
Workoutset.create(workout_id: 24, exercice_id: 27)
Workoutset.create(workout_id: 24, exercice_id: 30)
Workoutset.create(workout_id: 24, exercice_id: 16)
Workoutset.create(workout_id: 24, exercice_id: 28)
Workoutset.create(workout_id: 25, exercice_id: 3)
Workoutset.create(workout_id: 25, exercice_id: 18)
Workoutset.create(workout_id: 25, exercice_id: 4)
Workoutset.create(workout_id: 25, exercice_id: 17)
Workoutset.create(workout_id: 25, exercice_id: 25)
Workoutset.create(workout_id: 26, exercice_id: 5)
Workoutset.create(workout_id: 26, exercice_id: 3)
Workoutset.create(workout_id: 26, exercice_id: 19)
Workoutset.create(workout_id: 26, exercice_id: 6)
Workoutset.create(workout_id: 26, exercice_id: 32)
Workoutset.create(workout_id: 26, exercice_id: 39)
Workoutset.create(workout_id: 27, exercice_id: 13)
Workoutset.create(workout_id: 27, exercice_id: 33)
Workoutset.create(workout_id: 27, exercice_id: 14)
Workoutset.create(workout_id: 27, exercice_id: 15)
Workoutset.create(workout_id: 27, exercice_id: 7)
Workoutset.create(workout_id: 27, exercice_id: 35)
Workoutset.create(workout_id: 28, exercice_id: 18)
Workoutset.create(workout_id: 28, exercice_id: 3)
Workoutset.create(workout_id: 28, exercice_id: 17)
Workoutset.create(workout_id: 28, exercice_id: 8)
Workoutset.create(workout_id: 28, exercice_id: 12)
Workoutset.create(workout_id: 28, exercice_id: 38)
Workoutset.create(workout_id: 28, exercice_id: 37)
Workoutset.create(workout_id: 28, exercice_id: 31)
Workoutset.create(workout_id: 29, exercice_id: 5)
Workoutset.create(workout_id: 29, exercice_id: 11)
Workoutset.create(workout_id: 29, exercice_id: 27)
Workoutset.create(workout_id: 29, exercice_id: 9)
Workoutset.create(workout_id: 29, exercice_id: 10)
Workoutset.create(workout_id: 29, exercice_id: 30)
Workoutset.create(workout_id: 29, exercice_id: 16)
Workoutset.create(workout_id: 30, exercice_id: 13)
Workoutset.create(workout_id: 30, exercice_id: 14)
Workoutset.create(workout_id: 30, exercice_id: 7)
Workoutset.create(workout_id: 30, exercice_id: 33)
Workoutset.create(workout_id: 30, exercice_id: 35)
Workoutset.create(workout_id: 30, exercice_id: 15)
Workoutset.create(workout_id: 31, exercice_id: 20)
Workoutset.create(workout_id: 32, exercice_id: 9)
Workoutset.create(workout_id: 32, exercice_id: 5)
Workoutset.create(workout_id: 32, exercice_id: 11)
Workoutset.create(workout_id: 32, exercice_id: 27)
Workoutset.create(workout_id: 32, exercice_id: 10)
Workoutset.create(workout_id: 32, exercice_id: 30)
Workoutset.create(workout_id: 33, exercice_id: 13)
Workoutset.create(workout_id: 33, exercice_id: 14)
Workoutset.create(workout_id: 33, exercice_id: 7)
Workoutset.create(workout_id: 33, exercice_id: 33)
Workoutset.create(workout_id: 33, exercice_id: 35)
Workoutset.create(workout_id: 33, exercice_id: 15)
Workoutset.create(workout_id: 34, exercice_id: 13)
Workoutset.create(workout_id: 34, exercice_id: 14)
Workoutset.create(workout_id: 34, exercice_id: 7)
Workoutset.create(workout_id: 34, exercice_id: 33)
Workoutset.create(workout_id: 34, exercice_id: 15)
Repetition.create(workoutset_id: 1, quantity: 15, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 1, quantity: 15, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 1, quantity: 15, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 1, quantity: 15, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 2, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 2, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 2, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 2, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 3, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 3, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 3, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 3, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 4, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 4, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 4, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 4, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 5, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 5, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 5, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 5, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 6, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 6, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 6, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 6, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 7, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 7, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 7, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 7, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 8, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 8, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 8, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 8, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 9, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 9, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 9, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 9, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 10, quantity: 10, weight: 27, is_complete: true)
Repetition.create(workoutset_id: 10, quantity: 10, weight: 27, is_complete: true)
Repetition.create(workoutset_id: 10, quantity: 10, weight: 27, is_complete: true)
Repetition.create(workoutset_id: 10, quantity: 10, weight: 27, is_complete: true)
Repetition.create(workoutset_id: 11, quantity: 10, weight: 27, is_complete: true)
Repetition.create(workoutset_id: 11, quantity: 10, weight: 27, is_complete: true)
Repetition.create(workoutset_id: 11, quantity: 10, weight: 27, is_complete: true)
Repetition.create(workoutset_id: 11, quantity: 10, weight: 27, is_complete: true)
Repetition.create(workoutset_id: 12, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 12, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 12, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 12, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 13, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 13, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 13, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 13, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 14, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 14, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 14, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 14, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 15, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 15, quantity: 8, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 15, quantity: 10, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 15, quantity: 10, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 16, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 16, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 16, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 16, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 17, quantity: 10, weight: 10, is_complete: true)
Repetition.create(workoutset_id: 17, quantity: 10, weight: 10, is_complete: true)
Repetition.create(workoutset_id: 17, quantity: 10, weight: 10, is_complete: true)
Repetition.create(workoutset_id: 17, quantity: 10, weight: 10, is_complete: true)
Repetition.create(workoutset_id: 18, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 18, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 18, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 18, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 19, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 19, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 19, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 19, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 20, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 20, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 20, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 20, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 21, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 21, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 21, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 21, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 22, quantity: 10, weight: 24, is_complete: true)
Repetition.create(workoutset_id: 22, quantity: 10, weight: 24, is_complete: true)
Repetition.create(workoutset_id: 22, quantity: 10, weight: 24, is_complete: true)
Repetition.create(workoutset_id: 22, quantity: 10, weight: 24, is_complete: true)
Repetition.create(workoutset_id: 23, quantity: 10, weight: 54, is_complete: true)
Repetition.create(workoutset_id: 23, quantity: 10, weight: 54, is_complete: true)
Repetition.create(workoutset_id: 23, quantity: 10, weight: 54, is_complete: true)
Repetition.create(workoutset_id: 23, quantity: 10, weight: 54, is_complete: true)
Repetition.create(workoutset_id: 24, quantity: 10, weight: 54, is_complete: true)
Repetition.create(workoutset_id: 24, quantity: 10, weight: 54, is_complete: true)
Repetition.create(workoutset_id: 24, quantity: 10, weight: 54, is_complete: true)
Repetition.create(workoutset_id: 24, quantity: 10, weight: 54, is_complete: true)
Repetition.create(workoutset_id: 25, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 25, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 25, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 25, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 26, quantity: 10, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 26, quantity: 10, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 26, quantity: 10, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 26, quantity: 10, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 27, quantity: 10, weight: 25, is_complete: true)
Repetition.create(workoutset_id: 27, quantity: 10, weight: 25, is_complete: true)
Repetition.create(workoutset_id: 27, quantity: 10, weight: 25, is_complete: true)
Repetition.create(workoutset_id: 27, quantity: 10, weight: 25, is_complete: true)
Repetition.create(workoutset_id: 28, quantity: 10, weight: 73, is_complete: true)
Repetition.create(workoutset_id: 28, quantity: 10, weight: 73, is_complete: true)
Repetition.create(workoutset_id: 28, quantity: 10, weight: 73, is_complete: true)
Repetition.create(workoutset_id: 28, quantity: 10, weight: 73, is_complete: true)
Repetition.create(workoutset_id: 29, quantity: 10, weight: 64, is_complete: true)
Repetition.create(workoutset_id: 29, quantity: 10, weight: 64, is_complete: true)
Repetition.create(workoutset_id: 29, quantity: 10, weight: 64, is_complete: true)
Repetition.create(workoutset_id: 29, quantity: 10, weight: 64, is_complete: true)
Repetition.create(workoutset_id: 30, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 30, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 30, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 30, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 31, quantity: 8, weight: 8, is_complete: true)
Repetition.create(workoutset_id: 31, quantity: 10, weight: 8, is_complete: true)
Repetition.create(workoutset_id: 31, quantity: 10, weight: 8, is_complete: true)
Repetition.create(workoutset_id: 31, quantity: 8, weight: 8, is_complete: true)
Repetition.create(workoutset_id: 32, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 32, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 32, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 32, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 33, quantity: 10, weight: 23, is_complete: true)
Repetition.create(workoutset_id: 33, quantity: 10, weight: 23, is_complete: true)
Repetition.create(workoutset_id: 33, quantity: 10, weight: 23, is_complete: true)
Repetition.create(workoutset_id: 33, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 34, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 34, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 34, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 34, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 35, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 35, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 35, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 35, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 36, quantity: 9, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 36, quantity: 9, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 36, quantity: 9, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 36, quantity: 5, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 37, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 37, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 37, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 37, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 38, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 38, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 38, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 38, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 39, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 39, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 39, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 39, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 40, quantity: 10, weight: 77, is_complete: true)
Repetition.create(workoutset_id: 40, quantity: 10, weight: 77, is_complete: true)
Repetition.create(workoutset_id: 40, quantity: 10, weight: 77, is_complete: true)
Repetition.create(workoutset_id: 40, quantity: 10, weight: 77, is_complete: true)
Repetition.create(workoutset_id: 41, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 41, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 41, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 41, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 42, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 42, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 42, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 42, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 43, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 43, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 43, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 43, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 44, quantity: 10, weight: 24, is_complete: true)
Repetition.create(workoutset_id: 44, quantity: 10, weight: 24, is_complete: true)
Repetition.create(workoutset_id: 44, quantity: 10, weight: 24, is_complete: true)
Repetition.create(workoutset_id: 44, quantity: 10, weight: 24, is_complete: true)
Repetition.create(workoutset_id: 45, quantity: 10, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 45, quantity: 9, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 45, quantity: 8, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 45, quantity: 6, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 46, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 47, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 46, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 46, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 47, quantity: 10, weight: 65, is_complete: true)
Repetition.create(workoutset_id: 47, quantity: 6, weight: 65, is_complete: true)
Repetition.create(workoutset_id: 47, quantity: 2, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 47, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 46, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 48, quantity: 10, weight: 73, is_complete: true)
Repetition.create(workoutset_id: 48, quantity: 10, weight: 73, is_complete: true)
Repetition.create(workoutset_id: 48, quantity: 7, weight: 73, is_complete: true)
Repetition.create(workoutset_id: 48, quantity: 9, weight: 68, is_complete: true)
Repetition.create(workoutset_id: 49, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 49, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 49, quantity: 9, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 49, quantity: 7, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 50, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 50, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 50, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 50, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 51, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 51, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 51, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 51, quantity: 10, weight: 64, is_complete: true)
Repetition.create(workoutset_id: 52, quantity: 10, weight: 24, is_complete: true)
Repetition.create(workoutset_id: 52, quantity: 10, weight: 24, is_complete: true)
Repetition.create(workoutset_id: 52, quantity: 10, weight: 24, is_complete: true)
Repetition.create(workoutset_id: 52, quantity: 10, weight: 24, is_complete: true)
Repetition.create(workoutset_id: 53, quantity: 10, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 53, quantity: 10, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 53, quantity: 10, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 53, quantity: 10, weight: 80, is_complete: true)
Repetition.create(workoutset_id: 54, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 55, quantity: 10, weight: 10, is_complete: true)
Repetition.create(workoutset_id: 55, quantity: 10, weight: 10, is_complete: true)
Repetition.create(workoutset_id: 55, quantity: 10, weight: 10, is_complete: true)
Repetition.create(workoutset_id: 54, quantity: 9, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 54, quantity: 8, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 54, quantity: 10, weight: 45, is_complete: true)
Repetition.create(workoutset_id: 55, quantity: 10, weight: 10, is_complete: true)
Repetition.create(workoutset_id: 56, quantity: 10, weight: 77, is_complete: true)
Repetition.create(workoutset_id: 56, quantity: 10, weight: 77, is_complete: true)
Repetition.create(workoutset_id: 56, quantity: 10, weight: 77, is_complete: true)
Repetition.create(workoutset_id: 56, quantity: 10, weight: 77, is_complete: true)
Repetition.create(workoutset_id: 57, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 58, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 58, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 57, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 57, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 58, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 57, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 58, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 59, quantity: 10, weight: 25, is_complete: true)
Repetition.create(workoutset_id: 59, quantity: 10, weight: 30, is_complete: true)
Repetition.create(workoutset_id: 59, quantity: 10, weight: 30, is_complete: true)
Repetition.create(workoutset_id: 59, quantity: 10, weight: 30, is_complete: true)
Repetition.create(workoutset_id: 60, quantity: 8, weight: 8, is_complete: true)
Repetition.create(workoutset_id: 60, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 61, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 61, quantity: 10, weight: 45, is_complete: true)
Repetition.create(workoutset_id: 61, quantity: 10, weight: 45, is_complete: true)
Repetition.create(workoutset_id: 61, quantity: 10, weight: 45, is_complete: true)
Repetition.create(workoutset_id: 62, quantity: 8, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 63, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 63, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 62, quantity: 8, weight: 18, is_complete: true)
Repetition.create(workoutset_id: 62, quantity: 8, weight: 18, is_complete: true)
Repetition.create(workoutset_id: 63, quantity: 8, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 63, quantity: 8, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 62, quantity: 8, weight: 18, is_complete: true)
Repetition.create(workoutset_id: 64, quantity: 10, weight: 64, is_complete: true)
Repetition.create(workoutset_id: 64, quantity: 10, weight: 73, is_complete: true)
Repetition.create(workoutset_id: 64, quantity: 10, weight: 77, is_complete: true)
Repetition.create(workoutset_id: 64, quantity: 10, weight: 77, is_complete: true)
Repetition.create(workoutset_id: 65, quantity: 10, weight: 8, is_complete: true)
Repetition.create(workoutset_id: 65, quantity: 12, weight: 8, is_complete: true)
Repetition.create(workoutset_id: 65, quantity: 12, weight: 8, is_complete: true)
Repetition.create(workoutset_id: 66, quantity: 11, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 66, quantity: 10, weight: 80, is_complete: true)
Repetition.create(workoutset_id: 66, quantity: 9, weight: 80, is_complete: true)
Repetition.create(workoutset_id: 66, quantity: 6, weight: 80, is_complete: true)
Repetition.create(workoutset_id: 66, quantity: 4, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 67, quantity: 10, weight: 24, is_complete: true)
Repetition.create(workoutset_id: 67, quantity: 10, weight: 24, is_complete: true)
Repetition.create(workoutset_id: 67, quantity: 10, weight: 24, is_complete: true)
Repetition.create(workoutset_id: 68, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 68, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 69, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 69, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 68, quantity: 5, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 69, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 70, quantity: 10, weight: 65, is_complete: true)
Repetition.create(workoutset_id: 70, quantity: 9, weight: 65, is_complete: true)
Repetition.create(workoutset_id: 70, quantity: 5, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 70, quantity: 3, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 70, quantity: 9, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 71, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 71, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 71, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 71, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 72, quantity: 10, weight: 64, is_complete: true)
Repetition.create(workoutset_id: 73, quantity: 12, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 72, quantity: 10, weight: 68, is_complete: true)
Repetition.create(workoutset_id: 73, quantity: 8, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 73, quantity: 8, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 72, quantity: 9, weight: 68, is_complete: true)
Repetition.create(workoutset_id: 68, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 69, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 74, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 74, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 74, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 74, quantity: 5, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 75, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 75, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 76, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 76, quantity: 8, weight: 8, is_complete: true)
Repetition.create(workoutset_id: 75, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 76, quantity: 10, weight: 8, is_complete: true)
Repetition.create(workoutset_id: 76, quantity: 10, weight: 8, is_complete: true)
Repetition.create(workoutset_id: 75, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 77, quantity: 8, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 77, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 77, quantity: 8, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 78, quantity: 10, weight: 49, is_complete: true)
Repetition.create(workoutset_id: 79, quantity: 10, weight: 45, is_complete: true)
Repetition.create(workoutset_id: 79, quantity: 10, weight: 45, is_complete: true)
Repetition.create(workoutset_id: 78, quantity: 10, weight: 54, is_complete: true)
Repetition.create(workoutset_id: 80, quantity: 15, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 80, quantity: 15, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 80, quantity: 15, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 80, quantity: 15, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 78, quantity: 10, weight: 54, is_complete: true)
Repetition.create(workoutset_id: 79, quantity: 10, weight: 45, is_complete: true)
Repetition.create(workoutset_id: 79, quantity: 10, weight: 45, is_complete: true)
Repetition.create(workoutset_id: 78, quantity: 10, weight: 54, is_complete: true)
Repetition.create(workoutset_id: 81, quantity: 10, weight: 52, is_complete: true)
Repetition.create(workoutset_id: 81, quantity: 9, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 81, quantity: 9, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 82, quantity: 8, weight: 80, is_complete: true)
Repetition.create(workoutset_id: 82, quantity: 9, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 82, quantity: 5, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 82, quantity: 4, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 82, quantity: 9, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 83, quantity: 9, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 84, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 83, quantity: 8, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 84, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 83, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 84, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 84, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 83, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 85, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 85, quantity: 9, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 85, quantity: 5, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 85, quantity: 4, weight: 32.5, is_complete: true)
Repetition.create(workoutset_id: 85, quantity: 11, weight: 30, is_complete: true)
Repetition.create(workoutset_id: 86, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 86, quantity: 10, weight: 23, is_complete: true)
Repetition.create(workoutset_id: 86, quantity: 9, weight: 23, is_complete: true)
Repetition.create(workoutset_id: 86, quantity: 10, weight: 23, is_complete: true)
Repetition.create(workoutset_id: 87, quantity: 8, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 88, quantity: 10, weight: 80, is_complete: true)
Repetition.create(workoutset_id: 88, quantity: 6, weight: 80, is_complete: true)
Repetition.create(workoutset_id: 88, quantity: 4, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 88, quantity: 6, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 88, quantity: 4, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 89, quantity: 9, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 89, quantity: 9, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 89, quantity: 6, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 89, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 90, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 90, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 90, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 90, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 91, quantity: 10, weight: 27, is_complete: true)
Repetition.create(workoutset_id: 91, quantity: 10, weight: 32, is_complete: true)
Repetition.create(workoutset_id: 91, quantity: 10, weight: 27, is_complete: true)
Repetition.create(workoutset_id: 91, quantity: 10, weight: 32, is_complete: true)
Repetition.create(workoutset_id: 92, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 92, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 92, quantity: 9, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 92, quantity: 9, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 93, quantity: 10, weight: 64, is_complete: true)
Repetition.create(workoutset_id: 93, quantity: 10, weight: 68, is_complete: true)
Repetition.create(workoutset_id: 93, quantity: 10, weight: 68, is_complete: true)
Repetition.create(workoutset_id: 93, quantity: 10, weight: 73, is_complete: true)
Repetition.create(workoutset_id: 94, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 94, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 94, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 94, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 95, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 95, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 96, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 96, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 95, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 96, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 96, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 95, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 97, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 97, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 97, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 98, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 98, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 98, quantity: 8, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 98, quantity: 2, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 98, quantity: 5, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 98, quantity: 5, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 99, quantity: 10, weight: 22, is_complete: true)
Repetition.create(workoutset_id: 99, quantity: 10, weight: 22, is_complete: true)
Repetition.create(workoutset_id: 99, quantity: 10, weight: 22, is_complete: true)
Repetition.create(workoutset_id: 99, quantity: 10, weight: 22, is_complete: true)
Repetition.create(workoutset_id: 100, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 100, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 100, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 100, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 101, quantity: 10, weight: 49, is_complete: true)
Repetition.create(workoutset_id: 102, quantity: 9, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 102, quantity: 9, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 101, quantity: 9, weight: 49, is_complete: true)
Repetition.create(workoutset_id: 101, quantity: 9, weight: 49, is_complete: true)
Repetition.create(workoutset_id: 102, quantity: 9, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 102, quantity: 5, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 101, quantity: 9, weight: 49, is_complete: true)
Repetition.create(workoutset_id: 103, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 103, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 103, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 103, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 104, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 104, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 104, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 104, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 105, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 106, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 105, quantity: 10, weight: 45, is_complete: true)
Repetition.create(workoutset_id: 106, quantity: 10, weight: 45, is_complete: true)
Repetition.create(workoutset_id: 106, quantity: 9, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 105, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 107, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 107, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 107, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 108, quantity: 10, weight: 25, is_complete: true)
Repetition.create(workoutset_id: 108, quantity: 10, weight: 30, is_complete: true)
Repetition.create(workoutset_id: 109, quantity: 10, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 109, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 109, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 109, quantity: 9, weight: 80, is_complete: true)
Repetition.create(workoutset_id: 110, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 111, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 111, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 110, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 110, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 111, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 111, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 110, quantity: 8, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 112, quantity: 10, weight: 30, is_complete: true)
Repetition.create(workoutset_id: 112, quantity: 10, weight: 30, is_complete: true)
Repetition.create(workoutset_id: 112, quantity: 10, weight: 30, is_complete: true)
Repetition.create(workoutset_id: 112, quantity: 8, weight: 30, is_complete: true)
Repetition.create(workoutset_id: 113, quantity: 10, weight: 27, is_complete: true)
Repetition.create(workoutset_id: 113, quantity: 10, weight: 27, is_complete: true)
Repetition.create(workoutset_id: 114, quantity: 10, weight: 68, is_complete: true)
Repetition.create(workoutset_id: 114, quantity: 10, weight: 77, is_complete: true)
Repetition.create(workoutset_id: 114, quantity: 8, weight: 77, is_complete: true)
Repetition.create(workoutset_id: 114, quantity: 10, weight: 73, is_complete: true)
Repetition.create(workoutset_id: 115, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 116, quantity: 15, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 116, quantity: 15, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 116, quantity: 15, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 115, quantity: 10, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 115, quantity: 10, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 115, quantity: 10, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 117, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 117, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 118, quantity: 10, weight: 40, is_complete: true)
Repetition.create(workoutset_id: 118, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 119, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 119, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 119, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 118, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 119, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 118, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 120, quantity: 10, weight: 30, is_complete: true)
Repetition.create(workoutset_id: 120, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 120, quantity: 10, weight: 30, is_complete: true)
Repetition.create(workoutset_id: 120, quantity: 10, weight: 30, is_complete: true)
Repetition.create(workoutset_id: 121, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 121, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 121, quantity: 10, weight: 64, is_complete: true)
Repetition.create(workoutset_id: 121, quantity: 10, weight: 68, is_complete: true)
Repetition.create(workoutset_id: 122, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 122, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 122, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 122, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 123, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 123, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 123, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 123, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 124, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 124, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 124, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 124, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 125, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 125, quantity: 9, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 126, quantity: 10, weight: 49, is_complete: true)
Repetition.create(workoutset_id: 126, quantity: 9, weight: 49, is_complete: true)
Repetition.create(workoutset_id: 125, quantity: 5, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 126, quantity: 9, weight: 49, is_complete: true)
Repetition.create(workoutset_id: 125, quantity: 6, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 126, quantity: 9, weight: 49, is_complete: true)
Repetition.create(workoutset_id: 127, quantity: 10, weight: 22, is_complete: true)
Repetition.create(workoutset_id: 127, quantity: 10, weight: 22, is_complete: true)
Repetition.create(workoutset_id: 127, quantity: 10, weight: 22, is_complete: true)
Repetition.create(workoutset_id: 127, quantity: 10, weight: 22, is_complete: true)
Repetition.create(workoutset_id: 128, quantity: 10, weight: 40, is_complete: true)
Repetition.create(workoutset_id: 128, quantity: 10, weight: 40, is_complete: true)
Repetition.create(workoutset_id: 128, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 128, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 129, quantity: 10, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 129, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 129, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 129, quantity: 10, weight: 75, is_complete: true)
Repetition.create(workoutset_id: 130, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 131, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 131, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 130, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 130, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 131, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 131, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 130, quantity: 8, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 132, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 132, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 132, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 132, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 133, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 133, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 133, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 134, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 134, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 135, quantity: 10, weight: 4, is_complete: true)
Repetition.create(workoutset_id: 135, quantity: 10, weight: 4, is_complete: true)
Repetition.create(workoutset_id: 135, quantity: 10, weight: 4, is_complete: true)
Repetition.create(workoutset_id: 134, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 134, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 135, quantity: 10, weight: 4, is_complete: true)
Repetition.create(workoutset_id: 136, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 137, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 136, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 137, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 136, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 137, quantity: 9, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 138, quantity: 10, weight: 45, is_complete: true)
Repetition.create(workoutset_id: 138, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 138, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 139, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 139, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 139, quantity: 10, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 139, quantity: 10, weight: 70, is_complete: true)
Repetition.create(workoutset_id: 140, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 140, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 140, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 140, quantity: 8, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 141, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 141, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 141, quantity: 10, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 141, quantity: 8, weight: 35, is_complete: true)
Repetition.create(workoutset_id: 142, quantity: 10, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 142, quantity: 10, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 143, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 143, quantity: 10, weight: 64, is_complete: true)
Repetition.create(workoutset_id: 143, quantity: 10, weight: 64, is_complete: true)
Repetition.create(workoutset_id: 142, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 144, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 144, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 144, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 144, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 145, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 145, quantity: 10, weight: 65, is_complete: true)
Repetition.create(workoutset_id: 145, quantity: 10, weight: 65, is_complete: true)
Repetition.create(workoutset_id: 145, quantity: 8, weight: 65, is_complete: true)
Repetition.create(workoutset_id: 145, quantity: 3, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 146, quantity: 10, weight: 22, is_complete: true)
Repetition.create(workoutset_id: 146, quantity: 10, weight: 22, is_complete: true)
Repetition.create(workoutset_id: 146, quantity: 10, weight: 22, is_complete: true)
Repetition.create(workoutset_id: 146, quantity: 10, weight: 22, is_complete: true)
Repetition.create(workoutset_id: 147, quantity: 10, weight: 40, is_complete: true)
Repetition.create(workoutset_id: 147, quantity: 10, weight: 40, is_complete: true)
Repetition.create(workoutset_id: 147, quantity: 10, weight: 40, is_complete: true)
Repetition.create(workoutset_id: 147, quantity: 10, weight: 40, is_complete: true)
Repetition.create(workoutset_id: 148, quantity: 9, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 148, quantity: 9, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 148, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 148, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 149, quantity: 15, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 149, quantity: 15, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 149, quantity: 12, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 149, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 150, quantity: 10, weight: 18, is_complete: true)
Repetition.create(workoutset_id: 150, quantity: 9, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 150, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 150, quantity: 8, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 150, quantity: 2, weight: 18, is_complete: true)
Repetition.create(workoutset_id: 151, quantity: 10, weight: 30, is_complete: true)
Repetition.create(workoutset_id: 151, quantity: 10, weight: 30, is_complete: true)
Repetition.create(workoutset_id: 151, quantity: 10, weight: 30, is_complete: true)
Repetition.create(workoutset_id: 152, quantity: 10, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 152, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 151, quantity: 10, weight: 30, is_complete: true)
Repetition.create(workoutset_id: 152, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 153, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 153, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 152, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 153, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 153, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 154, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 154, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 154, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 154, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 155, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 155, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 155, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 155, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 156, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 156, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 156, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 156, quantity: 8, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 157, quantity: 10, weight: 60, is_complete: true)
Repetition.create(workoutset_id: 158, quantity: 10, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 157, quantity: 10, weight: 65, is_complete: true)
Repetition.create(workoutset_id: 158, quantity: 10, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 158, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 157, quantity: 10, weight: 65, is_complete: true)
Repetition.create(workoutset_id: 157, quantity: 10, weight: 65, is_complete: true)
Repetition.create(workoutset_id: 158, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 159, quantity: 10, weight: 27, is_complete: true)
Repetition.create(workoutset_id: 159, quantity: 10, weight: 27, is_complete: true)
Repetition.create(workoutset_id: 159, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 159, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 160, quantity: 10, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 160, quantity: 10, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 160, quantity: 10, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 160, quantity: 10, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 161, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 162, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 161, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 162, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 161, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 161, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 162, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 162, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 163, quantity: 19, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 163, quantity: 15, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 163, quantity: 15, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 164, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 164, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 164, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 164, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 165, quantity: 10, weight: 54, is_complete: true)
Repetition.create(workoutset_id: 165, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 165, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 165, quantity: 10, weight: 59, is_complete: true)
Repetition.create(workoutset_id: 166, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 167, quantity: 8, weight: 9, is_complete: true)
Repetition.create(workoutset_id: 167, quantity: 9, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 166, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 166, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 167, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 167, quantity: 10, weight: 14, is_complete: true)
Repetition.create(workoutset_id: 166, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 168, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 168, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 168, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 169, quantity: 10, weight: 40, is_complete: true)
Repetition.create(workoutset_id: 170, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 169, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 170, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 169, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 170, quantity: 9, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 171, quantity: 10, weight: 18, is_complete: true)
Repetition.create(workoutset_id: 171, quantity: 10, weight: 18, is_complete: true)
Repetition.create(workoutset_id: 171, quantity: 10, weight: 18, is_complete: true)
Repetition.create(workoutset_id: 171, quantity: 10, weight: 18, is_complete: true)
Repetition.create(workoutset_id: 172, quantity: 10, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 172, quantity: 10, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 172, quantity: 10, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 172, quantity: 10, weight: 12, is_complete: true)
Repetition.create(workoutset_id: 173, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 173, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 173, quantity: 10, weight: 4, is_complete: true)
Repetition.create(workoutset_id: 173, quantity: 10, weight: 4, is_complete: true)
Repetition.create(workoutset_id: 174, quantity: 10, weight: 25, is_complete: true)
Repetition.create(workoutset_id: 174, quantity: 10, weight: 25, is_complete: true)
Repetition.create(workoutset_id: 174, quantity: 10, weight: 25, is_complete: true)
Repetition.create(workoutset_id: 174, quantity: 10, weight: 27.5, is_complete: true)
Repetition.create(workoutset_id: 175, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 175, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 175, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 175, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 176, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 176, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 176, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 176, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 177, quantity: 10, weight: 45, is_complete: true)
Repetition.create(workoutset_id: 177, quantity: 10, weight: 49, is_complete: true)
Repetition.create(workoutset_id: 177, quantity: 10, weight: 49, is_complete: true)
Repetition.create(workoutset_id: 177, quantity: 10, weight: 49, is_complete: true)
Repetition.create(workoutset_id: 178, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 178, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 178, quantity: 8, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 178, quantity: 6, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 179, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 179, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 179, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 179, quantity: 10, weight: 55, is_complete: true)
Repetition.create(workoutset_id: 180, quantity: 10, weight: 36, is_complete: true)
Repetition.create(workoutset_id: 180, quantity: 10, weight: 45, is_complete: true)
Repetition.create(workoutset_id: 180, quantity: 10, weight: 49, is_complete: true)
Repetition.create(workoutset_id: 180, quantity: 10, weight: 54, is_complete: true)
Repetition.create(workoutset_id: 181, quantity: 8, weight: 8, is_complete: true)
Repetition.create(workoutset_id: 181, quantity: 10, weight: 8, is_complete: true)
Repetition.create(workoutset_id: 181, quantity: 9, weight: 8, is_complete: true)
Repetition.create(workoutset_id: 181, quantity: 10, weight: 0, is_complete: true)
Repetition.create(workoutset_id: 182, quantity: 10, weight: 40, is_complete: true)
Repetition.create(workoutset_id: 182, quantity: 10, weight: 45, is_complete: true)
Repetition.create(workoutset_id: 182, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 183, quantity: 10, weight: 36, is_complete: true)
Repetition.create(workoutset_id: 183, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 183, quantity: 10, weight: 41, is_complete: true)
Repetition.create(workoutset_id: 184, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 184, quantity: 10, weight: 18, is_complete: true)
Repetition.create(workoutset_id: 184, quantity: 10, weight: 18, is_complete: true)
Repetition.create(workoutset_id: 184, quantity: 10, weight: 18, is_complete: true)
Repetition.create(workoutset_id: 185, quantity: 10, weight: 8, is_complete: true)
Repetition.create(workoutset_id: 185, quantity: 10, weight: 10, is_complete: true)
Repetition.create(workoutset_id: 185, quantity: 10, weight: 10, is_complete: true)
Repetition.create(workoutset_id: 185, quantity: 10, weight: 10, is_complete: true)
Repetition.create(workoutset_id: 186, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 186, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 186, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 186, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 187, quantity: 10, weight: 25, is_complete: true)
Repetition.create(workoutset_id: 187, quantity: 10, weight: 25, is_complete: true)
Repetition.create(workoutset_id: 187, quantity: 10, weight: 25, is_complete: true)
Repetition.create(workoutset_id: 187, quantity: 10, weight: 25, is_complete: true)
Repetition.create(workoutset_id: 188, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 188, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 188, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 188, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 189, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 189, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 189, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 189, quantity: 10, weight: 50, is_complete: true)
Repetition.create(workoutset_id: 190, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 190, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 190, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 190, quantity: 10, weight: 16, is_complete: true)
Repetition.create(workoutset_id: 191, quantity: 10, weight: 10, is_complete: true)
Repetition.create(workoutset_id: 191, quantity: 10, weight: 10, is_complete: true)
Repetition.create(workoutset_id: 191, quantity: 10, weight: 10, is_complete: true)
Repetition.create(workoutset_id: 191, quantity: 10, weight: 10, is_complete: true)
Repetition.create(workoutset_id: 192, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 192, quantity: 10, weight: 4, is_complete: true)
Repetition.create(workoutset_id: 192, quantity: 10, weight: 4, is_complete: true)
Repetition.create(workoutset_id: 192, quantity: 10, weight: 6, is_complete: true)
Repetition.create(workoutset_id: 193, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 193, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 193, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 193, quantity: 10, weight: 20, is_complete: true)
Repetition.create(workoutset_id: 194, quantity: 10, weight: 40, is_complete: true)
Repetition.create(workoutset_id: 194, quantity: 10, weight: 40, is_complete: true)
Repetition.create(workoutset_id: 194, quantity: 10, weight: 40, is_complete: true)
Repetition.create(workoutset_id: 194, quantity: 10, weight: 40, is_complete: true)


#FEEDBACK
feedback = Workoutset.find(103)
feedback.remote_video_url = "http://res.cloudinary.com/duojdxafe/video/upload/v1537013773/IMG_7252.mp4"
feedback.feedback = "- l’effort du mouvement sur les talons est parfait on le voit très bien en vidéo seul défaut tes chaussures ( elles créent une réelle instabilité rotulienne alors que les chaussures d’haltérophilie son avec un socle en bois ou en carbone pour avoir un appui solide !)
 - tu es souple en ischio jambiers du coup tu as un soulève de terre avec peu d’abaissement des fessiers donc la charge de travail est plus en lombaires, si les charges augmentent il faudra que tu fléchisses plus tes jambes
- pour les omoplates tu peux faire un effort supplémentaire pour les resserrer (indicateur visuel: les pectoraux bien devant et les mains très basses bras tendu qui appui vers tes cuisses)  - garde la tête dans l’axe du corps pendant le mouvement pour éviter les douleurs cervicales"
feedback.save!



#MENU
menu1 = Workout.create(profile: profile_adrien, date: '2021-05-19', name: 'Menu 2021-05-19', type_habit: 'Meal')
menu2 = Workout.create(profile: profile_adrien, date: '2021-05-20', name: 'Menu 2021-05-20', type_habit: 'Meal')
menu3 = Workout.create(profile: profile_adrien, date: '2021-05-21', name: 'Menu 2021-05-21', type_habit: 'Meal')
Workoutset.create(workout: menu1, name: 'Meal Menu 1', exercice_id: 1)
Workoutset.create(workout: menu2, name: 'Meal Menu 2', exercice_id: 1)
Workoutset.create(workout: menu3, name: 'Meal Menu 3', exercice_id: 1)

